#+title: Direito Internacional da Família
#+Author: João Gomes de Almeida
#+Date: 7 de dezembro de 2022
#+LANGUAGE: pt
#+OPTIONS: date:nil toc:nil num:nil
#+LATEX_COMPILER: xelatex

* Caso prático

*Aníbal*, nacional português, casou com *Bianca*, nacional espanhola, em 1994. Fixaram domicílio conjugal em Madrid, em 1995. Do casamento, nasceram dois filhos, ambos luso-espanhois: *Carlos*, nascido em 15 de dezembro de 2005, e *Dani*, nascido em agosto de 2009.

*Aníbal* trabalha numa multinacional ligada ao turismo e às tecnologias da informação. Desde 2015 que exerce a sua atividade profissional ocasionalmente em Lisboa. Em março de 2021, fruto de uma promoção profissional, passou a exercer a sua atividade profissional de forma estável e permamente em Lisboa. Para o efeito, vive, durante os dias úteis da semana, num apartamento em Lisboa propriedade do seu pai e faz a sua vida social e profissional em Lisboa. As férias, dias feriados e fins de semanas passa-os em Madrid, na casa do casal, onde vivem *Bianca*, *Carlos* e *Dani*.

No dia 1 de outubro de 2022, *Aníbal* intenta ação de divórcio sem consentimento do outro cônjuge junto dos tribunais portugueses. No dia 15 de outubro de 2022, *Bianca* intenta ação de divórcio junto dos tribunais espanhois e, contestando a ação intentada por *Aníbal*, alega que os tribunais portugueses são internacionalmente incompetentes, pois os cônjuges (e os seus dois filhos) têm residência habitual em Madrid. Por sua vez, *Aníbal*, contestando a ação intentada junto dos tribunais espanhois, alega que a mesma não pode prosseguir enquanto não for proferida decisão de mérito na ação por si intentada junto dos tribunais portugueses.

*Questão 1:* Determine se os tribunais portugueses são internacionalmente competentes para julgar a ação intentada por *Aníbal* e como deve atuar o tribunal espanhol relativamente à ação intentada por *Bianca*.

Admita agora que *Aníbal* pede adicionalmente aos tribunais portugueses a regulação do exercício das responsabilidades parentais relativas a *Carlos* e *Dani*. Junta um documento particular, assinado por ele e *Bianca*, datado de 1 de junho de 2022, no qual consta o seguinte: "*Aníbal* e *Bianca* acordam, de forma livre e esclarecida, em atribuir competência internacional aos tribunais portugueses para decidir sobre a responsabilidade parental relativa aos seus dois filhos, *Carlos* e *Dani*, com expressa renúncia de qualquer outro".

*Questão 2:* Os tribunais portugueses são internacionalmente competentes para regular as responsabilidades parentais de *Carlos* e *Dani*?

*Questão 3:* /Quid iuris/ se já estivesse pendente uma ação de regulação do exercício das responsabilidades parentais de *Carlos* e *Dani* nos tribunais espanhois?

Admita agora que o tribunal português considerou-se internacionalmente competente. *Bianca*, apesar de regularmente citada, decide não participar no processo.

*Questão 4:* O tribunal português deve ouvir as crianças, *Carlos* e *Dani*? Em caso afirmativo, como deve proceder?

O tribunal português profere decisão em 2 de dezembro de 2022, decretando o divórcio e regulando as responsabilidades parentais: confiou a guarda das crianças a *Bianca* e regulou o direito de visita de *Aníbal*, os quais incluem contactos pela /Internet/ e por telefone, bem como encontros pessoais com as crianças, em Espanha, dois fins de semana por mês e por um período de 20 dias durante as férias do verão.

*Questão 5:* *Aníbal* requer ao tribunal português a emissão da certidão a que se refere o artigo 47.º. Deve o tribunal emitir essa certidão?

*Questão 6:* Admitindo que a certidão foi emitida e que *Aníbal* requereu a execução da decisão portuguesa perante a autoridade competente espanhola, pronuncie-se sobre as seguintes alegações de *Bianca*, que entende que deve ser recusada a execução da decisão portuguesa porque:

(i) *Bianca* não participou na mesma e a decisão obsta ao exercício das minhas responsabilidades parentais;

(ii) *Carlos* e *Dani* não foram ouvidos;

(iii) A decisão não foi tomada atendendo ao superior interesse da criança;

(iv) A decisão é incompatível com a decisão proferida pelos tribunais espanhois de 7 de dezembro de 2022, que concedeu apenas a *Aníbal* o contacto com as crianças por telefone e /Internet/ e um fim de semana a cada dois meses.

* Tópicos de resolução
** Questão 1: Determine se os tribunais portugueses são internacionalmente competentes para julgar a ação intentada por *Aníbal* e como deve atuar o tribunal espanhol relativamente à ação intentada por *Bianca*.

*1. Âmbitos de aplicação*. São quatro os âmbitos de aplicação do Regulamento Bruxelas II /ter/ (doravante os considerandos e artigos indicados sem indicação de fonte pertencem a este Regulamento).

/Em primeiro lugar/, há que verificar se a situação em litígio tem /incidência transfronteiriça/ (cf. considerandos 2 a 4). Nesta questão estamos perante uma ação de divórcio em que os cônjuges têm nacionalidade diferentes (portuguesa e espanhola). Isso é quanto basta para o litígio ser transnacional ou, nas expressões do Regulamento, implicar "um elemento internacional" (considerando 2) ou ter "implicações transfronteiriças" (considerandos 3 e 4).

/Em segundo lugar/, há que verificar se o âmbito de aplicação territorial, ou em razão do território, se encontra preenchido. O Regulamento é aplicável no território de todos os Estados-Membros, com exceção da Dinamarca (considerandos 95 e 96). Como a ação é intentada junto dos tribunais portugueses este âmbito de aplicação está preenchido.

/Em terceiro lugar/, há que verificar o âmbito de aplicação temporal. Nos termos do artigo 100.º, n.º 1, o Regulamento é aplicável apenas às ações intentadas, aos atos autênticos formalmente exarados e aos acordos registados a partir de 1 de agosto de 2022.

A determinação da data em que foi instaurada uma ação deve ser feita de acordo com o artigo 17.º. Temos um conceito autónomo tripartido. Há que olhar para o Direito processual do Estado-Membro do foro e determinar quando se considera intentada uma ação (neste caso de divórcio). No Direito processual português ela considera-se intentada na data em que foi apresentada ao tribunal a respetiva petição (art. 259.º do CPC). Logo, essa é a data relevante, nos termos do artigo 16.º, al. /a)/. A ação foi intentada em /1 de outubro de 2022/, logo depois de 1 de agosto de 2022. O âmbito de aplicação temporal está preenchido.

/Em quarto lugar/, há que verificar o âmbito de aplicação material. Para isso há que analisar o artigo 1.º. Nos termos do artigo 1.º, n.º 1, al. /a)/, o Regulamento aplica-se às ações matrimoniais (divórcio, separação judicial e anulação do casamento). Apesar de o Regulamento não definir os conceitos de casamento e divórcio, não há dúvidas que neste caso estamos perante um casamento "tradicional" (entre pessoas de sexo diferente) e perante uma ação que visa dissolver esse caso casamento.

*Nota extra:* discutiu-se, no Regulamento Bruxelas II /bis/ (o anterior), se o conceito de casamento aí perfilhado abrangia os casamentos entre pessoas do mesmo sexo. Neste novo Regulamento a utilização da expressão neutra "cônjuges" (cf. ponto 5.1 do Anexo II e ponto 6.1 do Anexo VII) quando antes se utilizavam as expressões "esposo" e "esposa" aponta no sentido de que o legislador pretendeu abranger os casamentos entre pessoas do mesmo sexo.

Verificados todos os âmbitos de aplicação, o Regulamento é aplicável.

*2. Regras de competência internacional em matéria matrimonial. Considerações gerais*. As regras de competência internacional estão previstas nos arts. 3.º a 6.º. Não estamos aqui perante uma conversão de uma separação em divórcio, nem foi efetuado pedido reconvencional, razão pela qual não são aplicáveis nem o art. 5.º, nem o art. 4.º.

A nova formulação do art. 6.º - que funde os anteriores arts. 6.º e 7.º do Regulamento Bruxelas II /bis/ - é, parece-nos, melhor e traduz de forma mais perfeita aquela que era a posição da doutrina maioritária e da jurisprudência do TJ sobre estes dois preceitos do Regulamento Bruxelas II /bis/.

Só é possível recorrer a outras normas (que não os arts. 3.º a 5.º) de competência internacional vigentes no Estado-Membro do foro (no caso Portugal) quando: (i) os arts. 3.º a 5.º não atribuem competência internacional a nenhum tribunal de qualquer Estado-Membro; e (ii) o cônjuge requerido não tem nacionalidade de um outro Estado-Membro ou, no caso da Irlanda, domicílio. No caso sob análise, nunca seria possível recorrer às normas de competência internacional de fonte interna (CPC) pois: os tribunais espanhois seriam competentes nos termos do artigo 3.º, al. /a)/, subal. /iii)/; e o cônjuge requerido (Bianca) tem nacionalidade de outro Estado-Membro (Espanha).

Conclusão: a competência internacional dos tribunais portugueses terá de estabelecer-se nos termos do art. 3.º; caso contrário, terão de se declarar incompetentes nos termos do art. 18.º.

*3. Concretização da residência habitual de Aníbal*. A questão que se coloca é a de saber qual é a residência habitual de *Aníbal*, uma vez que:

#+begin_quote
Em março de 2021, fruto de uma promoção profissional, passou a exercer a sua atividade profissional de forma estável e permamente em Lisboa. Para o efeito, vive, durante os dias úteis da semana, num apartamento em Lisboa propriedade do seu pai e faz a sua vida social e profissional em Lisboa. As férias, dias feriados e fins de semanas passa-os em Madrid, na casa do casal, onde vivem *Bianca*, *Carlos* e *Dani*.
#+end_quote

*Pergunta aos formandos:* será que *Aníbal* tem duas residências habituais: uma pessoal, em Madrid (Espanha), e outra profissional, em Lisboa (Portugal)?

A questão de saber se um cônjuge poderia ter, num dado momento, mais de um residência habitual já foi colocada ao TJ. No Acórdão de 25 de novembro de 2021, /IB contra FA/, C-289/20, [[https://curia.europa.eu/juris/liste.jsf?oqp=&for=&mat=or&jge=&td=%3BALL&jur=C%2CT%2CF&num=C-289%252F20&page=1&dates=&pcs=Oor&lg=&pro=&nat=or&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&language=pt&avg=&cid=663452][EU:C:2021:955]], em sede do Regulamento Bruxelas II /bis/, o TJ respondeu negativamente, concluindo que, num dado momento, uma pessoa só pode ter uma residência habitual.

Em síntese, foram estes os argumentos do TJ:

- Nenhuma das disposições do Regulamento Bruxelas II /bis/ emprega o conceito de residência habitual na forma plural.

- A jurisprudência do TJ sobre o conceito de residência habitual (do menor) acentua a residência habitual como centro permanente onde se situam os interesses da pessoa. Conclui que a ideia de centro de interesses não aponta no sentido de o conceito residência habitual poder suscitar problemas de conteúdo múltiplo, isto é, de permitir que, em simultâneo, uma pessoa tenha mais do que uma residência habitual.

- O TJ entende que com as normas atribuitivas de competência internacional em matéria de divórcio, separação judicial e anulação do casamento previstas no artigo 3.º, n.º 1, alínea /a)/, visa-se assegurar um equilíbrio entre a mobilidade das pessoas no interior da União Europeia e a segurança jurídica. O TJ considera que admitir a possibilidade de um cônjuge ter mais de uma residência habitual em simultâneo acarretaria o risco de a a competência internacional determinada, em última análise, não pelo critério da «residência habitual», mas por um critério baseado na simples residência de um ou de outro dos cônjuges, o que infringiria o Regulamento Bruxelas II /bis/. O risco à previsibilidade jurídica seria acrescido por outros regulamentos atribuírem competências noutras matérias, como obrigações alimentares ou regimes matrimoniais, ao tribunal internacionalmente competente para julgar a ação de divórcio, separação judicial ou anulação do casamento.

- Por fim, considerou o TJ que a sua anterior jurisprudência em matéria de plurinacionalidade comum dos cônjuges (Acórdão de 16 de julho de 2009, /Hadadi/, C-168/08, [[http://curia.europa.eu/juris/liste.jsf?language=pt&jur=C,T,F&num=C-168/08&td=ALL][EU:C:2009:474]]) não aponta em sentido contrário, pois a conclusão de que o conceito de nacionalidade consagrado no Regulamento Bruxelas II /bis/ não se encontra limitado à /nacionalidade efetiva/ não é relevante para a interpretação do conceito de residência habitual consagrado no artigo 3.º, n.º 1, alínea /a)/, do Regulamento Bruxelas II /bis/.

*Nota:* perguntar ao formandos se concordam com a argumentação do TJ.

Seguindo a jurisprudência do TJ, *Aníbal* /não/ tem duas residência habituais. Há agora que determinar se ele têm residência habitual em Madrid ou em Lisboa. A consequência desta opção é relevantíssima: se *Aníbal* tiver residência habitual em Madrid, então apenas os tribunais espanhois são internacionalmente competentes (art. 3.º, al. /a)/, subal. /i)/) e os tribunais portugueses devem oficiosamente declarar-se incompetentes (art. 18.º); se *Aníbal* tiver residência habitual em Portugal, então os tribunais portugueses também são internacionalmente competentes para julgar a ação de divórcio (art. 3.º, al. /a)/, subal. /vi)/).

*Pergunta:* perguntar aos formandos para concretizar a residência habitual de *Aníbal*.

A opinião do TJ parece ser a de que *Aníbal* teria residência habitual em Lisboa:

#+begin_quote
59      No presente processo, como resulta dos autos de que o Tribunal de Justiça dispõe, é pacífico que IB, nacional do Estado-Membro do órgão jurisdicional nacional no qual intentou a ação, preenchia o requisito de residência no território desse Estado-Membro pelo menos nos seis meses imediatamente anteriores à apresentação do seu pedido de dissolução do vínculo matrimonial, em aplicação do artigo 3.º, n.º 1, alínea a), sexto travessão, do Regulamento n.º 2201/2003. Está igualmente demonstrado que IB exercia, durante a semana, de forma permanente e estável, desde 2017, uma atividade profissional por tempo indeterminado em França, em cujo território ocupava um apartamento para efeitos do exercício da referida atividade.

60      Estes elementos visam demonstrar que a residência de IB no território desse Estado-Membro apresenta caráter estável e, além disso, permitem revelar, pelo menos, uma integração do interessado num ambiente social e cultural no referido Estado‑Membro.

61      Embora esses elementos deixem a priori pensar que os requisitos estabelecidos no artigo 3.º, n.º 1, alínea a), sexto travessão, do Regulamento n.º 2201/2003 podem estar preenchidos, incumbe, todavia, ao órgão jurisdicional de reenvio verificar se todas as circunstâncias de facto específicas do caso concreto permitem efetivamente considerar que o interessado transferiu a sua residência habitual para o território do Estado-Membro a que pertence o referido órgão jurisdicional.
#+end_quote

Aceitando que *Aníbal* tinha residência habitual em Lisboa, os tribunais portugueses dever-se-iam considerar internacionalmente competentes para julgar a ação.

*4. Litispendência e ações dependentes*. O regime de litispendência e ações dependentes em matéria de processos matrimoniais encontra-se previsto nos n.º 1 e n.º 3 do artigo 20.º. Este regime só é diretamente aplicável às situações de litispendência ou de ações dependentes de cariz transnacional envolvendo apenas tribunais de Estados-Membros.

No caso presente, temos ações intentadas em dois Estados-Membros. O regime é aplicável sempre que essas ações sejam ações abrangidas pelo âmbito de aplicação material do Regulamento (divórcio, separação judicial e anulação do casamento). Tal significa que o regime da litispendência e ações dependentes é acionado desde que duas ações matrimoniais sejam intentadas junto de tribunais de Estados-Membros diferentes e haja identidade de partes.

Resulta da redação do preceito que não existe uma hierarquização entre as ações matrimoniais. Consequentemente, uma qualquer ação matrimonial intentada num tribunal de um Estado-Membro impede, durante a sua pendência, que qualquer outra ação matrimonial seja julgada nos tribunais de outro Estado-Membro. É o caso pois existe identidade de partes e estão pendentes ações de divórcio em Portugal e em Espanha.

*5. Princípio da prioridade temporal*. O regime da litispendência e ações dependentes, assente na regra /qui prior est tempore potior est iure/ e na definição tripartida de instauração do processo (art. 17.º), permite resolver com facilidade a generalidade das situações de processos paralelos pendentes em tribunais de diversos Estados-Membros. No caso presente, a ação apresentada junto dos tribunais espanhois foi intentada mais tarde (em segundo lugar). Por esse motivo, e nos termos do artigo 20.º, n.º 1, o tribunal espanhol deve oficiosamente suspender a instância até que os tribunais portugueses estabeleçam (ou não) a sua competência.

*Aníbal* não tem razão quando afirma que os tribunais espanhois devem manter a suspensão da instância até que os tribunais portugueses profiram uma decisão sobre o mérito da causa. Nos termos do art. 20.º, n.ºs 1 e 3, os tribunais espanhois devem aguardar que os tribunais portugueses decidam se são ou não internacionalmente compententes. Se os tribunais portugueses decidirem que são internacionalmente /incompetentes/, os tribunais espanhois podem levantar a suspensão e prosseguir a ação; se os tribunais portugueses decidirem que são internacionalmente /competentes/, os tribunais espanhois devem declarar-se internacionalmente /incompetentes/, tendo *Bianca* a possibilidade de apresentar pedido reconvencional junto dos tribunais portugueses.

*Conclusão final:* caso se considere que *Aníbal* tem residência habitual em Lisboa, os tribunais portugueses seriam internacionalmente competentes e os tribunais espanhois deveriam suspender a instância no processo iniciado junto deles por *Bianca* até que os tribunais portugueses se declarassem internacional competentes, momento em que os tribunais espanhois se deveriam declarar internacionalmente incompetentes para julgar a ação apresentada por *Bianca*.

** Questão 2: Os tribunais portugueses são internacionalmente competentes para regular as responsabilidades parentais de *Carlos* e *Dani*?

*1. Revisitação dos âmbitos de aplicação*. Na questão anterior analisaram-se os âmbitos de aplicação tendo por base um litígio relativo a ações matrimoniais. Nesta questão introduz-se o problema das responsabilidades parentais, o que impõe uma reanálise (pelo menos de alguns) dos âmbitos de aplicação do Regulamento.

O âmbito de aplicação espacial e territorial mantêm-se sem alterações substantivas: a situação continua a ter incidência transfronteiriça e coloca-se perante tribunais portugueses, pelo que se suscita no território de um Estado-Membro vinculado à aplicação do Regulamento.

O Regulamento regula matérias distintas, embora conexas: as ações matrimoniais e as responsabilidades parentais dos filhos. Agora há uma extensão da matéria em litígio, mas ela é igualmente abrangida pelo âmbito de aplicação material, nos termos do artigo 1.º, n.º 1, al. /b)/, e n.º 2, al. /a)/.

Chama-se a atenção para os conceitos autónomos de responsabilidade parental, direito de guarda e direito de visita definidos no artigo 2.º, n.º 2, 7), 9) e 10).

Chama-se também a atenção para o facto de Carlos tem mais de 16 anos de idade (fará 17 no dia 15 de dezembro de 2022). Ainda assim, as normas sobre responsabilidade parental aplicam-se pois considera-se criança qualquer pessoa com menos de 18 anos (art. 2.º, n.º 2, 6)), mesmo que fosse emancipado (considerando 17).

O âmbito de aplicação material está preenchido.

Pode suscitar dúvidas o preenchimento do âmbito de aplicação temporal, uma vez que o acordo celebrado entre os progenitores relativo à competência dos tribunais portugueses data do dia 1 de junho de 2022, ou seja, o acordo foi celebrado em data /anterior/ a 1 de agosto de 2022.

Ora o artigo 100.º, n.º 1, estabelece que o Regulamento é aplicável apenas às ações intentadas, aos atos autênticos formalmente exarados e aos acordos registados a partir de 1 de agosto de 2022.

*Pergunta aos formandos:* está ou não está preenchido o âmbito de aplicação temporal?

*Resposta:* Está. O facto jurídico relevante é a data da instauração da ação e não a data da celebração do pacto de jurisdição.

Isso mesmo resulta de forma mais clara, pensa-se, da definição de "ato autêntico" e "acordo registado", que constam do art. 2.º, n.º 2, 2) e 3).

#+begin_quote
2)   «Ato autêntico»: um documento formalmente exarado ou registado como ato autêntico em qualquer Estado-Membro nas matérias abrangidas pelo âmbito de aplicação do presente regulamento e cuja autenticidade:

a) esteja associada à assinatura e ao conteúdo do ato, e

b) tenha sido confirmada por uma autoridade pública ou outra autoridade habilitada para esse efeito. Os Estados-Membros devem comunicar essas autoridades à Comissão nos termos do artigo 103.o;

3)   «Acordo», para efeitos do capítulo IV: um documento que não é um ato autêntico, tenha sido celebrado pelas partes em matérias abrangidas pelo âmbito de aplicação do presente regulamento e tenha sido registado por uma autoridade pública tal como comunicado por um Estado-Membro à Comissão nos termos do artigo 103.o para esse efeito;
#+end_quote

e também do considerando 14:

#+begin_quote
(14) De acordo com a jurisprudência do Tribunal de Justiça, o termo «tribunal» deverá ser interpretado em sentido lato, de modo que abranja também as autoridades administrativas ou outras autoridades como os notários que, em certas questões matrimoniais ou questões de responsabilidade parental, exercem a sua competência. Qualquer acordo aprovado pelo tribunal na sequência da análise do mérito em conformidade com o direito e os procedimentos nacionais deverá ser reconhecido ou aplicado como uma «decisão». *Outros acordos que adquiram um efeito jurídico vinculativo no Estado-Membro de origem na sequência da intervenção formal de uma autoridade pública ou de outra autoridade tal como comunicado por um Estado-Membro à Comissão para esse efeito, deverão produzir efeitos noutros Estados-Membros de acordo com as disposições específicas do presente regulamento sobre atos autênticos e acordos*. O presente regulamento não deverá permitir a livre circulação de simples acordos privados. No entanto, *os acordos que não sejam nem uma decisão nem um ato autêntico, mas que tenham sido registados por uma autoridade pública competente para o fazer deverão circular*. Essas autoridades públicas podem incluir os notários que efetuam o registo dos acordos, mesmo quando estes exercem uma profissão liberal. (negritos aditados)
#+end_quote

*2. A admissibilidade de pactos de jurisdição em matéria de responsabilidade parental: considerações gerais*. À semelhança do Regulamento Bruxelas II /bis/, permite-se, no art. 10.º que celebração de pactos de jurisdição que atribuem competência internacional aos tribunais de determinado Estado-Membro em matéria de responsabilidade parental. O art. 10.º é uma evolução face ao artigo 12.º do Regulamento Bruxelas II /bis/, já que prevê uma regulamentação /unitária/ para a admissibilidade dos pactos de jurisdição, deixando de distinguir entre pactos celebrados no contexto de ações matrimoniais e pactos celebrados no contexto de outras ações.

*3. Condições para o estabelecimento de competência através de um pacto: 1.ª condição cumulativa: ligação estreita da criança ao Estado-Membro designado (art. 10.º, n.º 1, al. /a)/)*.

O pacto só será admissível quando haja uma ligação estreita entre a criança e o Estado-Membro designado no pacto. No artigo 10.º, n.º 1, al. /a)/ indica-se uma lista /exemplificativa/ de situações em que há um conexão estreita.

No nosso caso, verifica-se pelo menos uma das ligações indicadas (as crianças têm nacionalidade portuguesa) e, dependendo do modo como foi concretizada a residência habitual de *Aníbal*, poderá existir uma outra ligação (um dos progenitores tem residência habitual em Portugal).

*4. 2.ª condição cumulativa: existência de acordo entre as partes no processo (art. 10.º, n.º 1, al. /b)/)*. Resulta das duas subalíneas do artigo 10.º, n.º 1, al. /b)/, que o acordo pode ser extrajudicial e, nesse caso, pode ser efetuado até à data da instauração do processo /ou/ pode ser efetuado no decurso e dentro do processo.

*Validade formal do acordo:* o art. 10.º, n.º 2, estabelece que, no caso de acordos extrajudiciais, o pacto deve ser celebrado por escrito, datado e assinado. No nosso caso, estes requisitos de forma uniformes estão cumpridos.

Chama-se, no entanto, a atenção para o considerando n.º 23, no qual se afirma que:

#+begin_quote
(...) Antes de exercer a sua competência com base num acordo ou numa aceitação relativos à atribuição de competência, o tribunal deverá analisar se o referido acordo ou aceitação teve por base uma escolha livre e informada das partes em causa e não é resultado de uma das partes ter tirado partido da situação ou posição fraca da outra parte. (...)
#+end_quote

Se o acordo fosse efetuado durante e dentro do processo, as regras formais que devem ser seguidas são as do Estado-Membro do foro (art. 10.º, n.º 2 e considerando n.º 23), relevando-se que o tribunal deve assegurar que todas as partes foram informadas do seu direito de não aceitar a competência (art. 10.º, n.º 2). Trata-se de uma obrigação algo semelhante à que existe no artigo 26.º, n.º 2, do Regulamento Bruxelas I /bis/.

*Identificação das partes:* o acordo deve ser celebrado pelas pessoas que são (ou serão) partes no processo. Regra geral, serão os progenitores das crianças. Podem também ser outras pessoas que sejam os titulares do exercício das responsabilidades parentais (por exemplo, no caso de colocação de crianças numa instituição). Todavia, há que prestar atenção à jurisprudência do TJ proferida em sede de Bruxelas II /bis/:

- No Acórdão de 31 de maio de 2018, /Valcheva/, C-335/17, [[https://curia.europa.eu/juris/liste.jsf?nat=or&mat=or&pcs=Oor&jur=C%2CT%2CF&num=C-335%252F17&for=&jge=&dates=&language=pt&pro=&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&oqp=&td=%3BALL&avg=&lg=&page=1&cid=191678][EU:C:2018:359]], o TJ concluiu que os avós a quem foi atribuído um direito de visita eram titulares da responsabilidade da criança;

- No Acórdão de 19 de abril de 2018, /Saponaro/, C-565/16, [[https://curia.europa.eu/juris/liste.jsf?nat=or&mat=or&pcs=Oor&jur=C%2CT%2CF&num=C-565%252F16&for=&jge=&dates=&language=pt&pro=&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&oqp=&td=%3BALL&avg=&lgrec=nl&lg=&page=1&cid=192583][EU:C:2018:265]], o TJ referiu, quando ao procurador público grego:

  #+begin_quote
29      Há, portanto, que considerar que um procurador que, segundo o direito nacional, tem a qualidade de parte no processo em ações como a que está em causa no processo principal e que representa o interesse do menor, é uma parte no processo, na aceção do artigo 12.°, n.° 3, alínea b), do Regulamento n.° 2201/2003. Por conseguinte, a sua oposição a uma extensão de competência não pode ser ignorada.
  #+end_quote

*Pergunta aos formandos:* atendendo à jurisprudência do caso /Saponaro/ como deve ser caracterizada a participação do Ministério Público nos processos de respnsabilidade parental que correm termos nos tribunais portugueses? Deve ser considerado, ou não, uma parte de pleno direito?

A resposta a esta questão é muito importante, porque nos termos do artigo 10.º, n.º 1, al. /b)/, e n.º 2, 2.º parágrafo, as partes de pleno direito podem opor-se aos pactos de jurisdição; havendo oposição, o pacto não produz efeitos.

*5. 3.ª condição cumulativa: o exercício da competência pelo tribunal designado no pacto tem de ser /no superior interesse da criança/ (art. 10.º, n.º 1, al. /c)/)*. Em primeiro lugar, chama-se a atenção para o considerando 19:

#+begin_quote
As regras de competência em matéria de responsabilidade parental *são definidas em função do superior interesse da criança e devem ser aplicadas em função desse interesse*. *Todas as referências ao superior interesse da criança deverão ser interpretadas à luz do artigo 24.º da Carta dos Direitos Fundamentais da União Europeia («Carta») e da Convenção das Nações Unidas sobre os Direitos da Criança, de 20 de novembro de 1989 («Convenção das Nações Unidas sobre os Direitos da Criança»)*, aplicadas ao abrigo do direito e dos procedimentos nacionais. (negritos aditados)
#+end_quote

O artigo 24.º da Carta estabelece:

#+begin_quote
Artigo 24.º

*Direitos das crianças*

1. As crianças têm direito à proteção e aos cuidados necessários ao seu bem-estar. Podem exprimir livremente a sua opinião, que será tomada em consideração nos assuntos que lhes digam respeito, em função da sua idade e maturidade.
2. Todos os atos relativos às crianças, quer praticados por entidades públicas, quer por instituições privadas, terão primacialmente em conta o interesse superior da criança.
3. Todas as crianças têm o direito de manter regularmente relações pessoais e contactos diretos com ambos os progenitores, exceto se isso for contrário aos seus interesses.
#+end_quote

O artigo 3.º da CNUDC estabelece:

#+begin_quote
Artigo 3.º
1. Todas as decisões relativas a crianças, adoptadas por instituições públicas ou privadas de protecção social, por tribunais, autoridades administrativas ou órgãos legislativos, terão primacialmente em conta o interesse superior da criança.
2. Os Estados Partes comprometem-se a garantir à criança a protecção e os cuidados necessários ao seu bem-estar, tendo em conta os direitos e deveres dos pais, representantes legais ou outras pessoas que a tenham legalmente a seu cargo e, para este efeito, tomam todas as medidas legislativas e administrativas adequadas.
3. Os Estados Partes garantem que o funcionamento de instituições, serviços e estabelecimentos que têm crianças a seu cargo e asseguram a sua protecção seja conforme às normas fixadas pelas autoridades competentes, nomeadamente nos domínios da segurança e saúde, relativamente ao número e qualificação do seu pessoal, bem como quanto à existência de uma adequada fiscalização.
#+end_quote

O superior interesse da criança na jurisprudência do TJ:

- No Acórdão de 12 de novembro de 2014, /L/, C-656/13, [[https://curia.europa.eu/juris/liste.jsf?nat=or&mat=or&pcs=Oor&jur=C%2CT%2CF&num=C-656%252F13&for=&jge=&dates=&language=pt&pro=&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&oqp=&td=%3BALL&avg=&lgrec=en&lg=&page=1&cid=197974][EU:C:2014:2364]], o TJ esclareceu que a análise do superior interesse da criança tem de ser casuística:

  #+begin_quote
  58      Importa acrescentar que, quando é submetido um processo a um tribunal nos termos do artigo 12.°, n.° 3, do Regulamento n.° 2201/2003, *o superior interesse da criança só pode ser assegurado através de uma análise, em cada caso concreto, da questão de saber se a extensão de competência pretendida é compatível com esse superior interesse*, e que uma extensão de competência, nos termos do artigo 12.°, n.° 3, do Regulamento n.° 2201/2003, apenas produz efeitos para o processo específico submetido ao tribunal cuja competência é objeto de extensão (v., neste sentido, acórdão E, EU:C:2014:2246, n.os 47 e 49). (negritos aditados)
  #+end_quote

- No Acórdão de 19 de abril de 2018, /Saponaro/, C-565/16, [[https://curia.europa.eu/juris/liste.jsf?nat=or&mat=or&pcs=Oor&jur=C%2CT%2CF&num=C-565%252F16&for=&jge=&dates=&language=pt&pro=&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&oqp=&td=%3BALL&avg=&lgrec=nl&lg=&page=1&cid=192583][EU:C:2018:26]], esclareceu que a aceitação da competência não deve ser suscetível de ter um impacto negativo na situação do menor:

  #+begin_quote
  No Acórdão de 27 de outubro de 2016, D. (C-428/15, EU:C:2016:819, n.º 58), relativo à interpretação do artigo 15.º do Regulamento n.º 2201/2013, consagrado à transferência para um tribunal mais bem colocado para apreciar a ação, o Tribunal de Justiça concluiu que a exigência de que a transferência sirva o superior interesse da criança implica que o tribunal competente se certifique, à luz das circunstâncias concretas do processo, de que a transferência equacionada deste último para um tribunal de outro Estado-Membro não é suscetível de ter um impacto negativo na situação do menor.
  #+end_quote

*Pergunta para os formandos:* a aceitação da competência pelo tribunal português acarreta o prejuízo para a situação do menor?

A resposta a esta questão deve ser dada no caso concreto e é decisiva para a aceitação da competência. O pacto só produzirá os seus efeitos se o tribunal português considerar que o exercício da competência que lhe é atribuída pelo pacto respeita o superior interesse criança. Em suma: o tribunal tem uma palavra decisiva a dizer quanto a admissibilidde do pacto.

** Questão 3: /Quid iuris/ se já estivesse pendente uma ação de regulação do exercício das responsabilidades parentais de *Carlos* e *Dani* nos tribunais espanhois?

*1. Litispendência em matéria de responsabilidade parental. Considerações gerais*. As regras de litispendência internacional em matéria de responsabilidade resultam do artigo 20.º, n.ºs 2 a 5.

Para que haja uma situação de litispendência terá de haver identidade de partes, pedido e causa de pedir e a responsabilidade parental tem de ser em relação a(s) mesma(s) criança(s).

Tudo isso se verifica no nosso caso.

*2. A regra geral: prioridade temporal*. Tal como na litispendência e ações dependentes em matéria de ações matrimoniais, a regra geral é a da prioridade temporal. Segundo esta regra, o tribunal demandado em segundo lugar (no caso, o tribunal português) deve suspender a instância até que esteja estabelecida a competência do tribunal demandado em primeiro lugar (no caso, o tribunal espanhol), nos termos do art. 19.º, n.º 2.

Se os tribunais espanhois se considerassem competentes, o tribunal português declarar-se-ia incompetente; se os tribunais espanhois se considerassem incompentetes, o tribunal português poderia prosseguir com a ação (art. 19.º, n.º 3).

*3. A /nova/ regra /especial/: prevalência dos tribunais designados através de um pacto de jurisdição /exclusivo/*. O Regulamento introduz no art. 20.º, n.ºs 4 e 5, um novo critério de resolução da litispendência. Este critério é claramente inspirado no artigo 31.º, n.ºs 2 e 3, do Regulamento Bruxelas I /bis/.

Estabelece-se a prevalência dos tribunais que tenham sido chamados a pronunciar-se na sequência de um pacto de jurisdição que lhes atribua competência exclusiva.

Segundo o art. 20.º, n.º 4, a partir do momento em que foi intentada a ação num tribunal em virtude de um pacto de jurisdição exclusivo, os tribunais dos outros Estados-Membros devem suspender quaisquer ações que estejam pendentes e em que haja a tríplice identidade, até que o tribunal competente por via do pacto estabeleça (ou não) que é competente.

Se se considerar competente, os outros devem declarar-se oficiosamente incompetentes (art. 20.º, n.º 5).

*4. Quando é que um pacto de jurisdição efetuado nos termos do art. 10.º atribui competência exclusiva?*

Como vimos acima, as partes podem fazer pactos de jurisdição: (i) até à data da instauração do processo e "fora" dele; ou (ii) durante o decurso do processo e "dentro" dele.

O Regulamento é explícito ao estabelecer que um pacto firmado no decurso e "dentro" do processo é um pacto de jurisdição que atribui competência exclusiva (art. 10.º, n.º 4).

Mas o pacto de jurisdição do nosso caso foi celebrado antes de intentada a ação. E sobre estes pactos, o art. 10.º /nada estabelece/ quanto à sua natureza. Já existe alguma divergência doutrinária sobre este ponto.

Há autores que defendem que o pacto de jurisdição celebrado "fora" do processo é sempre /não exclusivo/, isto é, só atribui competência aos tribunais designados, não retirando competência aos demais tribunais que seriam competentes em virtude de outras regras do Regulamento (mormente, os espanhois por serem os do Estado-Membro da residência habitual das crianças).

Outros autores defendem que nada impede as partes de atribuírem competência exclusiva ao pacto celebrado fora do processo; têm e de o fazer expressamente. O pacto de jurisdição exclusivo tem um efeito atributivo de competência e um efeito privativo de competência. Em favor desta tese, pode avançar-se a própria redação do artigo 20.º, n.º 4 e n.º 5, que mencionam todo o artigo 10.º e não apenas o artigo 10.º, n.º 1, al. /b)/, subal. /ii)/:

#+begin_quote
4.   Quando for chamado a pronunciar-se um tribunal de um Estado-Membro ao qual é atribuída *competência exclusiva por uma aceitação de competência referida no artigo 10.º*, os tribunais dos outros Estados-Membros suspendem a instância até ao momento em que o tribunal chamado a pronunciar-se com base no acordo ou na aceitação declare que não é competente for força do acordo ou da aceitação.

5.   Quando e na medida em que o tribunal estabeleceu a competência exclusiva por força da aceitação da competência *a que se refere o artigo 10.º*, os tribunais dos outros Estados-Membros declaram-se incompetentes a favor desse tribunal.
#+end_quote

E sobretudo o considerando 38:

#+begin_quote
(38) O funcionamento harmonioso da justiça obriga a minimizar a possibilidade de instaurar processos concorrentes e a evitar que sejam proferidas decisões inconciliáveis em Estados-Membros diferentes. Importa prever um mecanismo claro e eficaz para resolver os casos de litispendência e de conexão e para obviar aos problemas resultantes das divergências nacionais quanto à determinação do momento a partir do qual os processos são considerados pendentes. Para efeitos do presente regulamento, é conveniente fixar esta data de forma autónoma. Todavia, a fim de reforçar a eficácia dos acordos exclusivos relativos à atribuição de competência, as disposições do presente regulamento sobre litispendência *não deverão constituir um obstáculo caso os pais atribuam competência exclusiva aos tribunais de um Estado-Membro*.
#+end_quote

O considerando também não distingue entre pactos celebrados "dentro" e "fora" do processo.

Embora com dúvidas, eu inclino-me mais para esta solução.

Assim, se concordarem comigo, as partes atribuíram competência exclusiva aos tribunais portugueses, o que significa que, apesar de demandado em primeiro lugar, o tribunal espanhol deveria suspender oficiosamente a instância até que o tribunal português determinasse se é ou não internacionalmente competente para julgar a ação (art. 20.º, n.ºs 4 e 5).

** Questão 4: O tribunal português deve ouvir as crianças, *Carlos* e *Dani*? Em caso afirmativo, como deve proceder?

*1. Direito da criança expressar a sua opinião*. Uma das novidades deste Regulamento foi o acentuar do direito da criança expressar a sua opinião. Ele surge, em matéria de responsabilidade parental no art. 21.º; em matéria de rapto internacional de crianças, no art. 26.º; é uma das causas de recusa do reconhecimento de decisões em matéria de responsabilidade parental (art. 39.º, n.º 2); e a não audição da criança impede o recurso ao regime de reconhecimento das decisões "privilegiadas" (art. 47.º, n.º 3, al. /b)/).

No nosso caso, a norma relevante é o art. 21.º:

#+begin_quote
Artigo 21.º

Direito de a criança expressar a sua opinião

1.   No exercício da sua competência ao abrigo da secção 2 do presente capítulo, os tribunais dos Estados-Membros devem, em conformidade com o direito e os procedimentos nacionais, dar a uma criança que seja capaz de formar as suas próprias opiniões a oportunidade real e efetiva de as expressar, diretamente ou através de um representante ou de um organismo adequado.

2.   Se o tribunal, em conformidade com o direito e os procedimentos nacionais, der à criança a oportunidade de expressar as suas opiniões nos termos do presente artigo, deve ter devidamente em conta as opiniões da criança, em função da sua idade e maturidade.
#+end_quote

Uma das crianças tem mais de 16 anos e a outra mais de 13 anos. Não parece que estejamos perante um caso urgente. Assim, parece-me que as crianças devem ser ouvidas.

Veja-se o considerando 39:

#+begin_quote
Os processos em matéria de responsabilidade parental ao abrigo do presente regulamento, assim como os processos de regresso ao abrigo da Convenção da Haia de 1980, deverão, enquanto *princípio básico, dar a uma criança visada por um desses procedimentos e que seja capaz de formar as suas próprias opiniões, em conformidade com a jurisprudência do Tribunal de Justiça, a oportunidade real e efetiva de expressar essas opiniões, devendo estas ser devidamente tidas em conta na avaliação do superior interesse da criança*. A oportunidade de a criança expressar as suas próprias opiniões, em conformidade com o artigo 24.º, n.º 1, da Carta e à luz do artigo 12.º da Convenção das Nações Unidas sobre os Direitos da Criança, desempenha um papel importante na aplicação do presente regulamento. O regulamento deverá, contudo, deixar que sejam o direito e os procedimentos nacionais de cada Estado-Membro a determinar quem ouvirá a criança e como a criança será ouvida. Por conseguinte, o presente regulamento não deverá ter como propósito determinar se a criança deverá ser ouvida pelo próprio juiz pessoalmente ou por um perito com formação adequada que transmita a sua opinião ao tribunal posteriormente, ou se deverá ser ouvida na sala de audiências ou em qualquer outro local ou através de outros meios. *Além disso, embora continue a ser um direito da criança, ouvir a criança não pode constituir uma obrigação absoluta, devendo antes a questão ser avaliada tendo em conta o superior interesse da criança, por exemplo, nos casos que envolvam acordos entre as partes*.
#+end_quote

*2. Como ouvir as crianças?* Se concordarmos que as crianças devem ser ouvidas, resta agora saber como. O Regulamento não se pronuncia sobre esta matéria. Remete mesmo para o Direito vigente no Estado-Membro do foro. Caberá a esse Direito determinar se a criança é ouvida em tribunal ou noutro local, pelo juiz ou por um perito.

No entanto, deve-se chamar a atenção para o facto de as crianças residirem habitualmente em Espanha. Poderá haver colaboração da mãe e das crianças e estas deslocarem-se a Portugal para ser ouvidas. Mas também pode suceder o inverso.

Nestes casos, pode ser necessário recorrer à cooperação judiciária, mais propriamente, ao Regulamento (UE) 2020/1783 do Parlamento Europeu e do Conselho de 25 de novembro de 2020 relativo à cooperação entre os tribunais dos Estados-Membros no domínio da obtenção de prova em matéria civil ou comercial (obtenção de prova) (reformulação).

Sem pretensão de ser muito exaustivo, assinala-se que pode ser feito um pedido para a audição ser efetuada pelo tribunal requerido (eventualmente com a participação das partes e de um representante do tribunal - arts. 12.º a 14.º) /ou/, em alternativa, um pedido para a audição ser feita diretamente pelo tribunal português, através de videoconferência (art. 20.º). A principal diferença prática entre os meios indiretos e os meios diretos tem que ver com a coercividade: apenas nos primeiros se pode recorrer a medidas coercivas; no entanto, considerando que isto é um direito das crianças e não uma obrigação, parece-me duvidoso o recurso a meios coercivos para ultrapassar uma vontade /das crianças/ de não participarem no processo.

** Questão 5: *Aníbal* requer ao tribunal português a emissão da certidão a que se refere o artigo 47.º. Deve o tribunal emitir essa certidão?

*1. Decisões "privilegiadas"*. Há dois regimes de reconhecimento diferentes. O "normal" de reconhecimento automático (art. 39.º, n.º 1) e supressão de /exequatur/ (art. 34.º, n.º 1) e um para dois tipos de decisões "privilegiadas" (art. 42.º), em que são ainda mais limitados os fundamentos de recusa de reconhecimento, executoriedade e execução (art. 50.º).

As decisões privilegiadas são de dois tipos: (i) decisões que concedam direitos de visita; e (ii) uma decisão sobre o mérito relativa ao direito de guarda, proferida na sequência de uma decisão de recusa do regresso da criança ilicitamente deslocada ou retida (art. 42.º).

No nosso caso, temos uma decisão que, parcialmente, é uma decisão privilegiada, uma vez que concede a *Aníbal* direitos de visita.

*2. Condições para utilizar o regime de reconhecimento e execução das decisões privilegiadas*. É importante salientar que existem condições para se poder recorrer ao regime especial de reconhecimento das decisões privilegiadas. Estas constam do artigo 47.º, n.º 3:

#+begin_quote
a. O tribunal só emite a certidão se estiverem preenchidas as seguintes condições:

b. Todas as partes implicadas tiverem tido a oportunidade de ser ouvidas;

c. A criança tiver tido a oportunidade de expressar a sua opinião em conformidade com o artigo 21.º;

d. A decisão tiver sido proferida à revelia e:

   i) a parte revel tiver sido citada ou notificada do ato introdutório da instância ou ato equivalente em tempo útil e de forma a poder deduzir a sua defesa, ou

   ii) se estiver estabelecido que a parte revel aceitou a decisão de forma inequívoca.
#+end_quote

Diz-se no caso que a *Bianca* apesar de regularmente citada, decidiu não participar. Isto significa que estamos dentro da al. /d)/, subal. /i)/, não sendo óbice à emissão da certidão.

Terá de ter sido dada oportunidade às crianças de expressar a sua opinião, caso contrário não se poderá recorrer a este regime privilegiado.

Salienta-se que é opção da parte utilizar este regime especial ou o regime normal. Embora este regime seja mais vantajoso, nada impede a parte de pedir o reconhecimento e execução segundo o regime normal.

De igual modo também é possível recorrer ao regime normal de reconhecimento e execução quando não estejam previstas as condições para utilizar o regime especial.

*3. Conclusão*. Parece que o tribunal português deve emitir a certidão. Esta só pode ser atacada junto dos tribunais portugueses e com os fundamentos previstos no artigo 48.º (art. 47.º, n.º 6).


** Questão 6: Admitindo que a certidão foi emitida e que *Aníbal* requereu a execução da decisão portuguesa perante a autoridade competente espanhola, pronuncie-se sobre as seguintes alegações de *Bianca*, que entende que deve ser recusada a execução da decisão portuguesa porque:

*1. Análise dos fundamentos de recusa do regime normal e do regime especial*. Os fundamentos de recusa do regime normal estão previstos no artigo 39.º. Os fundamentos de recusa do regime especial estão previstos no artigo 50.º.

De seguida analisam-se as alegações de *Bianca*, à luz dos dois regimes de reconhecimento e execução.

*2. Bianca não participou na mesma e a decisão obsta ao exercício das minhas responsabilidades parentais*. /Regime especial:/ alegação irrelevante, porque não é fundamento de recusa (art. 50.º). Poderia ser motivo de impugnação da certidão, porque poderia estar em causa uma das condições necessárias para emissão da certidão (art. 48.º, n.º 2). /Regime normal:/ poderiam estar em causa dois fundamentos de recusa no regime normal (art. 39.º, al. /b)/ e /c)/).

Em qualquer caso, a alegação seria improcedente, porque *Bianca* foi regularmente citada, logo teve oportunidade para apresentar a sua defesa e para ser ouvida.

*3. Carlos e Dani não foram ouvidos*. Situação semelhante à anterior. /Regime especial:/ alegação irrelevante, porque não é fundamento de recusa (art. 50.º). Poderia ser motivo de impugnação da certidão, porque poderia estar em causa uma das condições necessárias para emissão da certidão (art. 48.º, n.º 2). /Regime normal:/ poderiam estar em causa dois fundamentos de recusa no regime normal (art. 39.º, n.º 2).

A alegação /só/ seria procedente /se/ o tribunal português /não tivesse dado oportunidade/ às crianças de serem ouvidas. Não é decisivo que as crianças não tenham sido ouvidas; decisivo é que tenham (ou não) tido oportunidade de serem ouvidas.

No regime normal assinala-se a diferente redação do artigo 39.º, n.º 2. Neste preceito estabelece-se que o tribunal do Estado-Membro requerido /pode/ recusar (poder discricionário); nos casos do artigo 39.º, n.º 1, o tribunal do Estado-Membro requerido /deve/ recusar (vinculatividade).

*4. A decisão não foi tomada atendendo ao superior interesse da criança*. /Regime especial:/ alegação irrelevante, não é fundamento de recusa. /Regime normal:/ pode ser relevante, mas a alegação é incompleta. Só será fundamento de recusa se o reconhecimento for manifestamente contrário à ordem pública do Estado-Membro requerido, tendo em conta o superior interesse da criança (art. 39.º, n.º 1, al. /a)/).

*5. A decisão é incompatível com a decisão proferida pelos tribunais
espanhois de 7 de dezembro de 2022, que concedeu apenas a Aníbal o contacto com as crianças por telefone e Internet e um fim de semana a cada dois meses*. A alegação é fundamento de recusa quer no /regime especial/ (art. 50.º), quer no /regime normal/ (art. 39.º, n.º 1, al. /d)/). Esta alegação seria sempre procedente e seria fundamento de recusa. A lógica é simples: entende-se que uma decisão posterior é mais conforme o superior interesse da criança, pois atendeu às circunstâncias mais atuais da criança.

*7. Fundamentos de suspensão ou recusa adicionais*. Para além do artigo 39.º (regime normal) e do art. 50.º (regime especial), há ainda a possibilidade de suspender ou recusar a execução de decisões em matéria de reponsabilidade parental:

- Quando execução expusesse a criança a um grave risco de danos físicos ou psicológicos devido a impedimentos temporários (suspensão) ou de carácter duradouro (recusa) que tenham surgido depois de a decisão ter sido proferida ou em virtude de qualquer outra alteração significativa das circunstâncias (art. 56.º, n.º 4 a 6);
- Com base no restante Direito vigente no Estado-Membro de execução, desde que este não seja incompatível com os artigos 41.º, 50.º e 56.º (art. 57.º).

*6. Conclusão*. Por força da última alegação, a execução da decisão portuguesa deveria ser recusada pelos tribunais espanhois.
