#+title: Direito Internacional da Família
#+Author: João Gomes de Almeida
#+Date: 14 de dezembro de 2022
#+LANGUAGE: pt
#+OPTIONS: date:nil toc:nil num:nil
#+LATEX_COMPILER: xelatex

* Caso prático 1

*Ana*, nacional portuguesa, e *Benny*, nacional irlandês, são os pais de duas crianças, ambas, luso-irlandesas, *Charles*, nascido em 1 de outubro de 2006, e *Diane*, nascida em 1 de dezembro de 2012.

A família residia habitualmente na Irlanda desde 2006. Em 10 de agosto de 2022, *Ana* viajou para Portugal com as crianças, para passar as férias de verão com os avós maternos das crianças. Em 30 de agosto de 2022, Ana comunica telefonicamente a *Benny* que não irá regressar à Irlanda e que ela e as duas crianças vão passar a viver em Portugal, tendo ela já encontrado uma casa para morarem e escolas para as duas crianças na cidade de Lisboa.

*Benny*, no dia 15 de setembro de 2022, intenta ação pedindo o regresso das crianças junto dos tribunais portugueses.

*Questão 1:* Sabendo que *Ana* e *Benny* não são casados entre si e que, segundo o Direito material irlandês, o pai natural dos menores não beneficia de pleno direito do direito de guarda, aprecie a admissibilidade da ação intentada por *Benny*.

*Questão 2:* Admita agora (e para as questões seguintes) que existia uma decisão judicial irlandesa que atribuía o direito de guarda relativo a *Charles* e a *Diane* conjuntamente a *Ana* e a *Benny*. A resposta alterava-se? E a data em que essa apreciação seria feita é de algum modo relevante?

*Questão 3:* *Ana* alega que era vítima de violência doméstica levada à cabo por *Benny*, juntando vários relatórios de várias deslocações às urgências médicas para tratar ferimentos físicos e declaração assinada por *Ella*, irlandesa vizinha do casal, em como tinha presenciado *Benny* injuriar, ameaçar e agredir *Ana*. Diga se o tribunal português:

(i) Pode proferir decisão de recusa sem ouvir *Benny*?

(ii) Pode proferir decisão de recusa sem conceder à conceder à criança a oportunidade de ser ouvida?

(iii) Pode proferir decisão de recusa se vigorar na Irlanda uma decisão judicial que impede *Benny* de se aproximar de *Ana* e das crianças e os serviços sociais Irlandeses estarem disponíveis para acolher *Ana* e as crianças no âmbito do programa nacional destinado a proteger as vítimas de violência doméstica?

*Questão 4*: Admita agora, que na pendência do processo, *Ana* e *Benny* acordam que a melhor solução para as crianças é o não regresso e que o direito de guarda sobre as mesmas deve ser atribuído a *Ana*, sem prejuízo de ser necessário o consentimento de *Benny* para efetuar uma alteração de residência habitual, e que *Benny* teria o direito de visita uma vez por mês e 15 dias durante as férias de verão. O tribunal português pode atribuir efeitos vinculativos a este acordo?

*Questão 5:* Considere agora que não houve acordo entre os progenitores e  que o tribunal português de primeira instância proferiu uma decisão de regresso.

(i) O tribunal pode declará-la executória, independentemente de qualquer recurso?

(ii) /Quid iuris/ se *Ana*, antecipando que a decisão lhe seria desfavorável, se deslocou, com as crianças, para França.

*Questão 6*: Admita agora que, após ouvir *Ana*, *Benny*, *Charles* e *Diane* o tribunal português proferiu uma decisão de não regresso. Durante a pendência do processo, *Benny* informou o tribunal português de que se encontra pendente, desde 1 de dezembro de 2022, em tribunal irlandês, uma ação relativa a regulação das responsabilidade parentais de *Charles* e *Diane*.

(i) Determine quais os tribunais que tinham competência internacional para regular o exercício das responsabilidades parentais.

(ii) O tribunal português fundamenta a decisão de não regresso com base na oposição da criança. Como deve atuar o tribunal português?

(iii) O tribunal irlandês profere, em 13 de dezembro de 2022 e após ouvir *Ana*, *Benny*, *Charles* e *Diane*, uma decisão que atribui o direito de guarda em exclusivo a *Benny* e concede direitos de visita a *Ana*, fixando a residência habitual das crianças na Irlanda. Como pode esta decisão ser executada em Portugal?


* Tópicos de resolução
