#+title: Direito Internacional da Família
#+Author: João Gomes de Almeida
#+Date: 14 de dezembro de 2022
#+LANGUAGE: pt
#+OPTIONS: date:nil toc:nil num:nil
#+LATEX_COMPILER: xelatex
#+cite_export: csl chicago-fullnote-bibliography.csl


* Caso prático

*Ana*, nacional portuguesa, e *Benny*, nacional irlandês, são os pais de duas crianças, ambas, luso-irlandesas, *Charles*, nascido em 1 de outubro de 2006, e *Diane*, nascida em 1 de dezembro de 2012.

A família residia habitualmente na Irlanda desde 2006. Em 10 de agosto de 2022, *Ana* viajou para Portugal com as crianças, para passar as férias de verão com os avós maternos das crianças. Em 30 de agosto de 2022, Ana comunica telefonicamente a *Benny* que não irá regressar à Irlanda e que ela e as duas crianças vão passar a viver em Portugal, tendo ela já encontrado uma casa para morarem e escolas para as duas crianças na cidade de Lisboa.

*Benny*, no dia 15 de setembro de 2022, intenta ação pedindo o regresso das crianças junto dos tribunais portugueses.

*Questão 1:* Sabendo que *Ana* e *Benny* não são casados entre si e que, segundo o Direito material irlandês, o pai natural dos menores não beneficia de pleno direito do direito de guarda, aprecie a admissibilidade da ação intentada por *Benny*.

*Questão 2:* Admita agora (e para as questões seguintes) que existia uma decisão judicial irlandesa que atribuía o direito de guarda relativo a *Charles* e a *Diane* conjuntamente a *Ana* e a *Benny*. A resposta alterava-se? E a data em que essa apreciação seria feita é de algum modo relevante?

*Questão 3:* *Ana* alega que era vítima de violência doméstica levada à cabo por *Benny*, juntando vários relatórios de várias deslocações às urgências médicas para tratar ferimentos físicos e declaração assinada por *Ella*, irlandesa vizinha do casal, em como tinha presenciado *Benny* injuriar, ameaçar e agredir *Ana*. Diga se o tribunal português:

(i) Pode proferir decisão de recusa sem ouvir *Benny*?

(ii) Pode proferir decisão de recusa sem conceder à criança a oportunidade de ser ouvida?

(iii) Pode proferir decisão de recusa se vigorar na Irlanda uma decisão judicial que impede *Benny* de se aproximar de *Ana* e das crianças e os serviços sociais Irlandeses estarem disponíveis para acolher *Ana* e as crianças no âmbito do programa nacional destinado a proteger as vítimas de violência doméstica?

*Questão 4*: Admita agora, que na pendência do processo, *Ana* e *Benny* acordam que a melhor solução para as crianças é o não regresso e que o direito de guarda sobre as mesmas deve ser atribuído a *Ana*, sem prejuízo de ser necessário o consentimento de *Benny* para efetuar uma alteração de residência habitual, e que *Benny* teria o direito de visita uma vez por mês e 15 dias durante as férias de verão. O tribunal português pode atribuir efeitos vinculativos a este acordo?

*Questão 5:* Considere agora que não houve acordo entre os progenitores e  que o tribunal português de primeira instância proferiu uma decisão de regresso.

(i) O tribunal pode declará-la executória, independentemente de qualquer recurso?

(ii) /Quid iuris/ se *Ana*, antecipando que a decisão lhe seria desfavorável, se deslocou, com as crianças, para França.

*Questão 6*: Admita agora que, após ouvir *Ana*, *Benny*, *Charles* e *Diane* o tribunal português proferiu uma decisão de não regresso. Durante a pendência do processo, *Benny* informou o tribunal português de que se encontra pendente, desde 1 de dezembro de 2022, em tribunal irlandês, uma ação relativa a regulação das responsabilidade parentais de *Charles* e *Diane*.

(i) Determine quais os tribunais que tinham competência internacional para regular o exercício das responsabilidades parentais.

(ii) O tribunal português fundamenta a decisão de não regresso com base na oposição da criança. Como deve atuar o tribunal português?

(iii) O tribunal irlandês profere, em 13 de dezembro de 2022 e após ouvir *Ana*, *Benny*, *Charles* e *Diane*, uma decisão que atribui o direito de guarda em exclusivo a *Benny* e concede direitos de visita a *Ana*, fixando a residência habitual das crianças na Irlanda. Como pode esta decisão ser executada em Portugal?

* Tópicos de resolução
** *Questão 1:* Sabendo que *Ana* e *Benny* não são casados entre si e que, segundo o Direito material irlandês, o pai natural dos menores não beneficia de pleno direito do direito de guarda, aprecie a admissibilidade da ação intentada por *Benny*.

*1. Âmbitos de aplicação.* São quatro os âmbitos de aplicação do Regulamento Bruxelas II /ter/ (doravante os considerandos e artigos indicados sem indicação de fonte pertencem a este Regulamento).

/Em primeiro lugar/, há que verificar se a situação em litígio tem /incidência transfronteiriça/ (cf. considerandos 2 a 4). Nesta questão estamos perante uma alegada situação de rapto internacional de crianças e basta a deslocação dos menores da Irlanda para Portugal para verificarmos que a situação implica "um elemento internacional" (considerando 2) ou ter "implicações transfronteiriças" (considerandos 3 e 4).

/Em segundo lugar/, há que verificar se o âmbito de aplicação territorial, ou em razão do território, se encontra preenchido. O Regulamento é aplicável no território de todos os Estados-Membros, com exceção da Dinamarca (considerandos 95 e 96). Como a ação é intentada junto dos tribunais portugueses este âmbito de aplicação está preenchido.

/Em terceiro lugar/, há que verificar o âmbito de aplicação temporal. Nos termos do artigo 100.º, n.º 1, o Regulamento é aplicável apenas às ações intentadas, aos atos autênticos formalmente exarados e aos acordos registados a partir de 1 de agosto de 2022.

A determinação da data em que foi instaurada uma ação deve ser feita de acordo com o artigo 17.º. Temos um conceito autónomo tripartido. Há que olhar para o Direito processual do Estado-Membro do foro e determinar quando se considera intentada uma ação (neste caso de divórcio). No Direito processual português ela considera-se intentada na data em que foi apresentada ao tribunal a respetiva petição (art. 259.º do CPC). Logo, essa é a data relevante, nos termos do artigo 16.º, al. /a)/. A ação de regresso foi intentada em /15 de setembro de 2022/, logo depois de 1 de agosto de 2022. O âmbito de aplicação temporal está preenchido.

/Em quarto lugar/, há que verificar o âmbito de aplicação material. Para isso há que analisar o artigo 1.º. Nos termos do artigo 1.º, n.º 3, as regras do Regulamento Bruxelas II /ter/ são aplicáveis aos casos de rapto internacional de crianças que afetem mais de um Estado-Membro, em complemento das regras da Convenção da Haia de 1980 sobre Rapto Internacional de Crianças (doravante Convenção da Haia de 1980). Logo, o âmbito de aplicação material está verificado.

Verificados todos os âmbitos de aplicação, o Regulamento é aplicável.

*2. Âmbitos de aplicação da Convenção da Haia de 1980.* Vejamos, agora, sucintamente, os âmbitos de aplicação da Convenção da Haia de 1980.

/Em primeiro lugar/ a Convenção só se preocupa com a deslocação ou retenção ilícitas que tenham um carácter internacional

/Em segundo lugar/ a Convenção só se aplica nos casos em que a criança ilicitamente deslocada ou retida tinha residência habitual num Estado Contratante imediatamente antes dessa deslocação ou retenção (art. 4.º da Convenção da Haia de 1980). A criança tem de ter idade inferior a 16 anos.

/Em terceiro lugar/, as regras da Convenção aplicam-se apenas as deslocações ou retenções ilícitas que ocorreram depois da entrada em vigor da Convenção nos dois Estados Contratantes envolvidos (o da residência habitual anterior e o da deslocação ou retenção ilícitas), nos termos do art. 35.º da Convenção da Haia de 1980. No seio da União Europeia, esta questão já não é relevante atendendo a que a Convenção se encontra em vigor há muito tempo (em Portugal desde 1 de dezembro de 1983 e na Irlanda desde 1 de outubro de 1991), mas a questão pode ser relevante para as relações com Estados Contratantes recentes (a Convenção entrou em vigor no Botswana no passado dia 1 de fevereiro).

/Em quarto lugar/ o âmbito de aplicação material é o da /deslocação ou retenção ilícitas/ de crianças, conforme resulta dos artigos 1.º e 3.º da Convenção da Haia de 1980.

*3. Relação entre a Convenção da Haia de 1980 e o Regulamento Bruxelas II /ter/*. Aqui o Regulamento Bruxelas II /ter/ torna mais claro o que já resultava do considerando n.º 17 do Regulamento Bruxelas II /bis/ e dos pontos 77 e 78 do [[https://curia.europa.eu/juris/liste.jsf?nat=or&mat=or&pcs=Oor&jur=C%2CT%2CF&num=1%252F13&for=&jge=&dates=&language=pt&pro=&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&oqp=&td=%3BALL&avg=&lg=&page=1&cid=25022][Parecer 1/13]] do Tribunal de Justiça da União Europeia:

#+begin_quote
"(17)  Em caso de deslocação ou de retenção ilícitas de uma criança, deve ser obtido sem demora o seu regresso; para o efeito, deverá continuar a aplicar-se a Convenção de Haia de 25 de Outubro de 1980, completada pelas disposições do presente regulamento, nomeadamente o artigo 11.º. (...)"
#+end_quote

e

#+begin_quote
"77 O Regulamento n.° 2201/2003 completa e precisa, nomeadamente no seu artigo 11.°, as referidas regras convencionais. (...)

78 Do conteúdo de todas as disposições do Regulamento n.º 2201/2003 evocadas no número anterior decorre que as mesmas se baseiam nas regras da Convenção de Haia de 1980 ou preveem consequências a extrair da aplicação destas últimas. Estas duas categorias de disposições constituem assim um conjunto normativo indivisível, aplicável aos procedimentos de regresso de crianças ilicitamente deslocadas dentro da União."
#+end_quote

No Regulamento Bruxelas II /ter/ consagrou-se esta ideia no artigo 96.º:

#+begin_quote
"Se uma criança tiver sido ilicitamente transferida ou retida num Estado-Membro que não o da sua residência habitual imediatamente antes da deslocação ou retenção ilícitas, continuam a ser aplicáveis as disposições da Convenção da Haia de 1980, complementadas pelos capítulos III e VI do presente regulamento. Se uma decisão que decreta o regresso da criança nos termos da Convenção da Haia de 1980 que foi proferida num Estado-Membro tiver de ser reconhecida e executada noutro Estado-Membro na sequência de nova deslocação ou retenção ilícita da criança, é aplicável o capítulo IV."
#+end_quote

Em suma, as regras do Regulamento Bruxelas II /ter/ só serão aplicáveis nos casos em que a anterior residência habitual da criança e o local da sua deslocação ou retenção ilícitas sejam Estados-Membros da União Europeia vinculados ao Regulamento Bruxelas II /ter/ (todos, com exceção da Dinamarca).

*4. Conceito de deslocação ou retenção ilícitas*. Quer a Convenção da Haia de 1980, quer o Regulamento Bruxelas II /ter/, definem o conceito de deslocação ou retenção ilícita.

A Convenção da Haia de 1980, no seu artigo 3.º:

#+begin_quote
"A deslocação ou a retenção de uma criança é considerada ilícita quando:

a) Tenha sido efectivada em violação de um direito de custódia atribuído a uma pessoa ou a uma instituição ou a qualquer outro organismo, individual ou conjuntamente, pela lei do Estado onde a criança tenha a sua residência habitual imediatamente antes da sua transferência ou da sua retenção; e
b) Este direito estiver a ser exercido de maneira efectiva, individualmente ou em conjunto, no momento da transferência ou da retenção, ou o devesse estar se tais acontecimentos não tivessem ocorrido.

O direito de custódia referido na alínea a) pode designadamente resultar quer de uma atribuição de pleno direito, quer de uma decisão judicial ou administrativa, quer de um acordo vigente segundo o direito deste Estado."
#+end_quote

O Regulamento Bruxelas II /ter/ na alínea 11) do n.º 2 do artigo 2.º:

#+begin_quote
"11) «Deslocação ou retenção ilícitas»: a deslocação ou a retenção de uma criança, quando:
a) viole o direito de guarda conferido por decisão judicial, por atribuição de pleno direito ou por acordo em vigor nos termos do direito do Estado-Membro onde a criança tinha a sua residência habitual imediatamente antes da deslocação ou retenção; e
b) no momento da deslocação ou retenção, o direito de guarda estivesse a ser efetivamente exercido, quer conjunta, quer separadamente, ou devesse estar a sê-lo, caso não tivesse ocorrido a deslocação ou retenção."
#+end_quote

As duas definições são, essencialmente, /idênticas/. Verifica-se uma aparente omissão na definição do Regulamento Bruxelas II /ter/, que não menciona a atribuição do direito de guarda por decisão administrativa. Dizemos aparente, porque o conceito de decisão judicial no Regulamento Bruxelas II /ter/ permite também abarcar decisão de autoridades administrativas quando elas tenham competência em matéria de responsabilidade parental (cf. artigo 2.º, n.º 1 e n.º 2, alínea 1) do Regulamento Bruxelas II /ter/).

No caso é mais próximo de uma situação de retenção do que de deslocação, pois parece que a deslocação pelo período das férias não tinha merecido oposição do outro progenitor.

Mas para, neste caso, a retenção ser considerada /ilícita/ têm de se verificar dois pressupostos: (i) que *Benny* tenha o direito de guarda e (ii) que *Benny* estivesse efetivamente a exercê-lo, não fosse a retenção.

Nos casos em que não haja decisão judicial, decisão administrativa ou acordo sobre a atribuição das responsabilidade parentais, a questão vai depender de saber se *Benny* tinha ou não o direito de guarda sobre as crianças por mero efeito do Direito aplicável.

Antes da deslocação, as crianças tinham residência habitual na Irlanda. De acordo com a Convenção da Haia de 1996 (aplicável quer na Irlanda quer em Portugal), a atribuição de responsabilidades parentais /ope legis/ é regulada pela lei da residência habitual da criança, ou seja, pela lei irlandesa. Segundo a lei irlandesa, ao pai não casado com a mãe não é atribuído, por mero efeito da lei, o direito de guarda sobre as crianças. Conclusão: *Benny* não era titular do direito de guarda e, como tal, a retenção feita por *Ana* das crianças em Portugal não pode ser considerada uma deslocação ou retenção ilícitas, pois não violou o (inexistente) direito de guarda de *Benny*.

A retenção é lícita.

*Pergunta para os formandos:* será que esta solução (que depende do direito material irlandês) viola a Carta dos Direitos Fundamentais da União Europeia, em particular o seu art. 7.º e 24.º?

#+begin_quote
"Todas as pessoas têm direito ao respeito pela sua vida privada e familiar, pelo seu domicílio e pelas suas comunicações." (Artigo 7.º)
#+end_quote

#+begin_quote
"1 As crianças têm direito à proteção e aos cuidados necessários ao seu bem-estar. Podem exprimir livremente a sua opinião, que será tomada em consideração nos assuntos que lhes digam respeito, em função da sua idade e maturidade.

2 Todos os atos relativos às crianças, quer praticados por entidades públicas, quer por instituições privadas, terão primacialmente em conta o interesse superior da criança.

3 Todas as crianças têm o direito de manter regularmente relações pessoais e contactos diretos com ambos os progenitores, exceto se isso for contrário aos seus interesses." (Artigo 24.º)
#+end_quote

A questão foi abordado pelo TJ no Acórdão de 5 de outubro de 2010, /J. McB contra L.E./, C-400/10 PPU, EU:C:2010:582.

O TJ concluíu, à semelhança do TEDH, que não há violação da carta na não atribuição /ope legis/ ao pai natural não casado, desde que o Direito do Estado permite que ele peça a atribuição antes da deslocação ou retenção (cons. 52 a 64).

** *Questão 2:* Admita agora (e para as questões seguintes) que existia uma decisão judicial irlandesa que atribuía o direito de guarda relativo a *Charles* e a *Diane* conjuntamente a *Ana* e a *Benny*. A resposta alterava-se? E a data em que essa apreciação seria feita é de algum modo relevante?

*5. Direito de guarda proveniente de decisão judicial*. Nesta segunda questão, foi atribuído a *Ana* e a *Benny*, por decisão judicial irlandesa, um direito de guarda conjunto sobre as crianças.

Deste modo, *Ana* não pode decidir /sozinha/ a residência habitual das crianças. A retenção das crianças em Portugal para além do período de férias constitui uma violação do direito de guarda de *Benny* e é, por isso, uma retenção ilícita.

*Questão /ad latere/:* a questão não menciona, mas podem surgir problemas complexos quando se tratem de decisões judiciais que atribuem a guarda a apenas uma pessoa, e que, apesar de não transitadas em julgado, produzam os seus efeitos.

/Quid iuris/ se uma nova decisão irlandesa atribuísse o direito de guarda e o de fixar a residência habitual das crianças apenas a *Ana*. Com base nessa decisão *Ana* mudasse a residência habitual das crianças para Portugal e, posteriormente à mudança, *Benny* recorresse da decisão e os tribunais superiores anulassem a mesma, passado um ano. Houve ou não deslocação ilícita das crianças por parte de *Ana*?

/Resposta:/ a questão é muito sensível, mas foi já abordada pelo TJ no Acórdão de 9 de outubro de 2014, /C contra M/, EU:C:2014:2268. Neste acórdão ele decidiu:

#+begin_quote
1)      Os artigos 2.°, ponto 11, e 11.° do Regulamento (CE) n.° 2201/2003 do Conselho, de 27 de novembro de 2003, relativo à competência, ao reconhecimento e à execução de decisões em matéria matrimonial e em matéria de responsabilidade parental e que revoga o Regulamento (CE) n.° 1347/2000, devem ser interpretados no sentido de que, quando a deslocação da criança ocorreu em conformidade com uma decisão judicial executória provisoriamente que foi em seguida revogada por uma decisão judicial que fixava a residência da criança no domicílio do progenitor que permanece no Estado‑Membro de origem, o órgão jurisdicional do Estado‑Membro para onde a criança foi deslocada, chamado a pronunciar‑se sobre um pedido de regresso da criança, deve verificar, ao proceder à avaliação de todas as circunstâncias específicas do caso, se a criança ainda tinha a sua residência habitual no Estado‑Membro de origem imediatamente antes da retenção ilícita alegada. No âmbito desta avaliação, há que ter em conta o facto de a decisão judicial que autorizava a deslocação poder ser executada provisoriamente e ter sido objeto de recurso.

2)      O Regulamento n.° 2201/2003 deve ser interpretado no sentido de que, quando a deslocação da criança ocorreu em conformidade com uma decisão judicial executória provisoriamente que foi em seguida revogada por uma decisão judicial que fixava a residência da criança no domicílio do progenitor que permanece no Estado‑Membro de origem, a retenção da criança noutro Estado‑Membro na sequência dessa segunda decisão é ilícita e o artigo 11.° desse regulamento é aplicável se se considerar que a criança ainda tinha a sua residência habitual no referido Estado‑Membro imediatamente antes dessa retenção. Se, pelo contrário, se considerar que nesse momento a criança já não tinha a sua residência habitual no Estado‑Membro de origem, a decisão que julga improcedente o pedido de regresso baseado nessa disposição é adotada sem prejuízo da aplicação das regras relativas ao reconhecimento e à execução de decisões proferidas num Estado‑Membro previstas no capítulo III do mesmo regulamento.
#+end_quote

Em suma, tudo parece assentar no decurso de tempo e na questão de saber se a criança mudou (licitamente) de residência habitual enquanto vigorou a decisão que conferia o direito de guarda exclusivo a *Ana*.

*6. O conceito de criança para efeitos de rapto internacional de crianças*. De acordo com o caso, *Charles* nasceu em 1 de outubro de 2006 e *Diane*, nasceu em 1 de dezembro de 2012.

A ação foi intentada a 15 de setembro de 2022, ou seja a 15 dias de *Charles* fazer 16 anos e quando *Diane* tinha 9 anos de idade (faria 10 anos cerca de mês e meio depois da data de propositura da ação).

De acordo com o artigo 2.º, n.º 2, alínea 6) do Regulamento Bruxelas II /ter/, criança, para efeitos do Regulamento, é qualquer pessoa com menos de 18 anos. Aparentemente ambos seriam crianças.

É necessário, porém, salientar que o conceito de criança na Convenção da Haia de 1980 é diferente, como decorre do seu artigo 4.º:

#+begin_quote
"A Convenção aplica-se a qualquer criança com residência habitual num Estado Contratante, imediatamente antes da violação do direito de custódia ou de visita. A aplicação da Convenção cessa quando a criança atingir a idade de 16 anos."
#+end_quote

Não nos podemos esquecer que resulta as regras do Regulamento Bruxelas II /ter/ em matéria de rapto internacional de crianças /visam complementar/ a Convenção da Haia de 1980. Como tal, e logicamente, o conceito de criança relevante para efeitos de rapto internacional de crianças /é o da Convenção e não o do Regulamento/. Isso mesmo é expressamente referido no considerando n.º 17 do Regulamento e resulta também do artigo 22.º do Regulamento Bruxelas II /ter/:

#+begin_quote
"(...) A Convenção da Haia de 1980, e, consequentemente, também o capítulo III do presente regulamento, que complementa a aplicação da Convenção da Haia de 1980 nas relações entre os Estados-Membros, deverá continuar a ser aplicável às crianças até aos 16 anos de idade." (considerando n.º 17)

"Os artigos 23.º a 29.º e o capítulo VI do presente regulamento são aplicáveis e complementam a Convenção da Haia de 1980 quando uma pessoa, instituição ou outro organismo que alegue a violação do direito de guarda pedir, diretamente ou com a assistência de uma autoridade central, a um tribunal de um Estado-Membro que profira uma decisão, baseada na Convenção da Haia de 1980, que ordene o regresso de *uma criança com menos de 16 anos* que tenha sido ilicitamente deslocada ou retida num Estado-Membro que não o da sua residência habitual imediatamente antes da deslocação ou retenção ilícitas." (art. 22.º)
#+end_quote

Em suma: os artigos 23.º a 29.º e o Capítulo IV do Regulamento só são aplicáveis a situações de rapto internacional de crianças, entendendo-se como tal as pessoas com menos de 16 anos de idade.

*7. Idade da criança e momento em que é aferida a competência*. A regra geral do Regulamento é a costumeira: a competência internacional dos tribunais afere-se com referência à data em que foi proposta a ação.

A 15 de setembro de 2022, as duas crianças tinham menos de 16 anos de idade. Porém, a 1 de outubro de 2022, *Charles* terá 16 anos de idade. A Convenção da Haia de 1980, no seu artigo 4.º estabelece como regra que "a aplicação da Convenção cessa quando a criança atingir a idade de 16 anos."

Como se refere no Relatório Explicativo, a Convenção adotou a posição mais restritiva:

#+begin_quote
"(...) no action or decision based upon the Convention's provisions can be taken with regard to a child after its sixteenth birthday."[cite:@perez-vera1980 p. 450, ponto 77]
#+end_quote

Isto significa, quanto a *Charles*, que muito dificilmente seria possível proferir uma decisão de regresso, uma vez que ela teria de ser proferida em menos de 15 dias.

Recorda-se que o novo artigo 24.º estabelece regras mais detalhadas sobre o "processo judicial expedito", estabelecendo nomeadamente que:
1. deve ser usado o procedimento mais expedito no direito nacional (art. 24.º/1 - perguntar aos formandos qual é o procedimento a adotar em Portugal);
2. Salvo casos excecionais, o tribunal de 1.ª instância deve decidir no prazo de seis semanas (art. 24.º/2);
3. Salvo casos excecionais, o tribunal de instância superior deve decidir no prazo de seis semanas contadas da data em que estiver em condições para examinar o recurso (art. 24.º/3).

** *Questão 3:* *Ana* alega que era vítima de violência doméstica levada à cabo por *Benny*, juntando vários relatórios de várias deslocações às urgências médicas para tratar ferimentos físicos e declaração assinada por *Ella*, irlandesa vizinha do casal, em como tinha presenciado *Benny* injuriar, ameaçar e agredir *Ana*. Diga se o tribunal português:
*** (i) Pode proferir decisão de recusa sem ouvir *Benny*?

*8. Oportunidade de audição da parte que requer o regresso*. As regras do Regulamento Bruxelas II /ter/ visam promover o regresso, sem demora, da criança ilicitamente deslocada ou retida ao Estado-Membro da sua residência habitual antes da deslocação ou retenção ilícitas. Deste modo, compreende-se que a audição da parte que requer o regresso /é sempre obrigatória/ quando o tribunal do Estado-Membro da deslocação ou retenção pretende proferir uma decisão que /não/ ordene o regresso da criança (art. 27.º, n.º 1).

Deste modo, o tribunal /não pode/ proferir uma decisão de recusa sem previamente dar a *Benny* a oportunidade de ser ouvido no processo. Em certa medida, parece-me que esta regra assegura simultaneamente o direito a julgamento equitativo, assegurando que a parte que requer o regresso da criança tem a oportunidade de expor o seu caso perante o tribunal, e, secundariamente, funciona como dissuasor da emissão de decisões de recusa de regresso.

Nos casos em que o tribunal do Estado-Membro da deslocação ou retenção ilícitas profira uma decisão de regresso da criança ao anterior Estado-Membro da residência habitual, essa decisão pode ser feita dispensando a audição da parte que requer o regresso. Neste caso é o superior interesse da criança, conjugado com a necessidade de um procedimento célere e o alinhamento entre a decisão e o pedido efetuado pelo parte que requer o regresso, que permite a dispensa de audição.

*Pergunta aos formandos:* imaginem que o tribunal português profere decisão de recusa sem dar a *Benny* a oportunidade de ser ouvido? Como pode ele reagir?

/Resposta:/ recorrer da decisão com fundamento em violação do artigo 24.º/1.

*** (ii) Pode proferir decisão de recusa sem conceder à criança a oportunidade de ser ouvida?

*9. O direito da criança a ser ouvida*. É indiscutível, a luz dos artigos 26.º e 21.º do Regulamento Bruxelas II /ter/ que a criança tem o direito de expressar a sua opnião num processo de regresso.

Estas normas, conjuntamente com o considerando 39.º, são bem vindas porque destacam e acentuam a visibilidade deste direito da criança, que já existia e está consagrado quer no artigo 24.º da Carta dos Direitos Fundamentais da União Europeia, quer no artigo 12.º da Convenção das Nações Unidas sobre os Direitos da Criança.

No nosso caso prático, o foco será a *Diane* porque, como vimos anteriormente, *Charles* rapidamente terá 16 anos de idade e deixará de poder recair sobre ele qualquer tipo de decisão proferida nos termos da Convenção da Haia de 1980.

*Diane* tem 9 anos de idade, quase 10, aquando da propositura da ação.

O tribunal deve, em primeiro lugar, verificar se a crinaça é capaz de formar as suas próprias opiniões. Nessa análise, deve atender-se à idade e ao grau de maturidade (até por referência ao artigo 24.º, n.º 1 da Carta), mas a nova redação não limita a aferição a esses elementos. A idade e o grau de maturidade são agora indicados como elementos para aferir o "peso" que o tribunal deve dar às opiniões das crianças.

Se concluir que a criança é capaz de formar as suas próprias opiniões, o tribunal deve dar uma oportunidade real e efetiva à crianças de as prestar (art. 21.º/1 /in fine/ e /ex vi/ art. 26.º). Cabe ao Direito nacional determinar o modo como a audição da criança se processa, o que deve ser feito atendendo ao superior interesse da criança (audição direta ou por representante; audição por perito nomeado pelo Tribunal; videoconferência).

Apesar do que se tem dito, não é possível responder negativamente à questão. Em regra, o Regulamento Bruxelas II /ter/ pretende destacar que a criança tem direito a ser ouvido nos processos de rapto internacional que a envolvam. Mas esse é um direito e não uma obrigação da criança, o que significa, desde logo, que a criança pode ser recusar participar no processo, sem que tal afete a margem decisória do tribunal. Sempre se dirá que este é o caso simples: pois aqui, seria ainda dada à criança a /oportunidade/ de ser ouvida, ela é que prescindiria dessa oportunidade. Mas, de igual modo, o tribunal pode, num determinado caso concreto, concluir que a criança não tem capacidade para formar as suas próprias opiniões, o que o dispensa de dar a oportunidade à criança de ser ouvida.

Outra situação mais duvidosa e complexa, é aquela em que o tribunal conclui que a criança é capaz de formar as suas próprias opiniões (e, regra geral e fazendo uma generalização abstracta, diremos que as crianças de 9/10 anos de idade são capazes de formas as suas próprias opiniões), mas conclui igualmente que o superior interesse da criança, no caso concreto, aponta no sentido de não a ouvir, porque, por exemplo, a audição deve, no caso concreto, ser feita presencialmente e a deslocação da criança acarreta riscos. Este caso é mais duvidoso, porque duas ordens de razão: (i) o artigo 21.º/1 parece apontar no sentido de que o tribunal deve dar oportunidade de audição às crianças /sempre que elas sejam capazes de formar as suas opiniões/; (ii) a generalidade das situações em que pode haver risco para as crianças, este pode ser mitigado ou eliminado por outras vias de audição (por perito, por videoconferência, por representante, deslocando um representante do tribunal à criança, recorrendo a audição efetuada nos termos do Regulamento de Obtenção de Prova através de um tribunal do Estado onde está a criança).

Em contraponto, o considerando 39 parece admitir a possibilidade de prescindir da audição da criança, se tal for a solução mais adequada aos seus superiores interesses, dando como exemplo os casos que envolvam acordos entre as partes:

#+begin_quote
"Além disso, embora continue a ser um direito da criança, ouvir a criança não pode constituir uma obrigação absoluta, devendo antes a questão ser avaliada tendo em conta o superior interesse da criança, por exemplo, nos casos que envolvam acordos entre as partes."
#+end_quote

De qualquer modo, não há um /dever incondicional/ de dar à criança uma oportunidade de ser ouvida. Há apenas esse dever, depois de o tribunal aferir se ela é ou não capaz de formar as suas próprias opiniões.

Em conclusão: atendendo à idade de *Ana* parece-me que o Tribunal deveria conceder-lhe a oportunidade de ser ouvida. Ainda assim, tal poderia não suceder caso o tribunal concluísse que ela não era capaz de formar as suas próprias opiniões.

*** (iii) Pode proferir decisão de recusa se vigorar na Irlanda uma decisão judicial que impede *Benny* de se aproximar de *Ana* e das crianças e os serviços sociais Irlandeses estarem disponíveis para acolher *Ana* e as crianças no âmbito do programa nacional destinado a proteger as vítimas de violência doméstica?

*10. Fundamentos de recusa da Convenção da Haia de 1980. Considerações iniciais*. São vários os fundamentos de uma decisão de recusa de regresso na Convenção da Haia de 1980:
1. A ação de regresso foi instaurada passado mais de um ano da data da deslocação ou retenção ilícitas e a criança já se encontra integrada no seu novo ambiente (art. 12.º, 2.º parágrafo);
2. O requerente não exercia efetivamente o direito de guarda na época da deslocação ou retenção ilícitas ou consentiu posteriormente com a deslocação ou retenção ilícitas (art. 13.º, alínea /a)/);
3. Existe um risco grave de a criança, no seu regresso, ficar sujeita a perigos de ordem física ou psíquica, ou, de qualquer outro modo, a ficar numa situação intolerável (art. 13.º, alínea /b)/);
4. A criança opõe-se ao regresso e tem já uma idade e um grau de maturidade que permitem tomar em consideração as suas opiniões sobre este assunto (art. 13.º, 2.º parágrafo);
5. O regresso da criança não é consentâneo com os princípios fundamentais do Estado requerido relativos à protecção dos direitos do homem e das liberdades fundamentais (art. 20.º).

Estes fundamentos de recusa são exceções à regra geral da Convenção de regresso, sem demoras, da criança ao Estado da sua residência habitual antes da deslocação ou retenção ilícitas. Por isso, devem ser objeto de uma interpretação estrita.

*11. O fundamento assente no risco grave para a criança (art. 13.º, alínea /b)/ da Convenção da Haia de 1980*. O preceito prevê três tipos de riscos graves para a criança:
1. Risco grave de que a criança, no seu regresso, fique sujeita a perigos de ordem física;
2. Risco grave de que a criança, no seu regresso, fique sujeita a perigos de ordem psíquica; ou
3. Risco grave de que a criança, no seu regresso, fique, de qualquer outro modo, numa situação intolerável.

Cada um destes tipos de risco grave pode fundamentar, por si só, uma decisão de recusa de regresso da criança. Ainda assim, os três tipos de riscos graves costumam ser alegados em conjunto.

*12. Risco grave da criança*. Pode discutir-se, em tese, se há um risco grave da criança, quando o que é alegado é violência doméstica do progenitor que ficou sem a criança sobre o progenitor raptor.

Em primeiro lugar, assinala-se que embora os riscos devem ser aferidos em função da criança, tem sido entendido que, em circunstâncias excecionais, os perigos para os progenitores podem criar um risco grave para a criança.

Em segundo lugar, pode afirmar-se que, em caso de violência doméstica de um progenitor sobre outro, a vivência dessa situação pela criança pode constituir um risco grave de perigo de ordem psíquica, bem como um risco grave de separação do progenitor raptor, caso este entenda que não tem condições de segurança para regressar, na sequência de uma decisão de regresso da criança.

/Pergunta aos formandos:/ o que acham? Há aqui uma situação de risco grave para a criança?

*13. Alegação de risco grave*.  tribunal deve considerar se as alegações são dessa natureza e se contêm pormenor e substância suficientes para constituir um risco grave. É muito improvável que alegações amplas ou gerais sejam suficientes. No caso, a *Ana* parece apresentar elementos concretos que consubstanciam as alegações de violência doméstica.

/Pergunta aos formandos:/ o que acham? os elementos probatórios são suficientes para uma análise /prima facie/?

*14. Possibilidade de decretar medidas provisórias que permitam o contacto entre a criança e o progenitor que ficou sem a criança*. art. 27.º/2

*15. Medidas de proteção e comunicação*. art. 27.º/3 a 5

** *Questão 4*: Admita agora, que na pendência do processo, *Ana* e *Benny* acordam que a melhor solução para as crianças é o não regresso e que o direito de guarda sobre as mesmas deve ser atribuído a *Ana*, sem prejuízo de ser necessário o consentimento de *Benny* para efetuar uma alteração de residência habitual, e que *Benny* teria o direito de visita uma vez por mês e 15 dias durante as férias de verão. O tribunal português pode atribuir efeitos vinculativos a este acordo?

*16. A procura de uma solução e a possibilidade de concentração de competências em matéria de rapto e de responsabilidade parental*. O Regulamento introduz no artigo 25.º a possibilidade de recorrer a meios alternativos de resolução de litígios, em particular a mediação. Esta possibilidade de recurso a mediação, desde que não protela o proferimento de uma decisão, é vista com bons olhos, uma vez que uma solução alcançada com o acordo de ambos os progenitores é uma solução com maiores probabilidades de ser por ambos cumprida.

Para além disso, há que referir que a solução acordada por *Ana* e *Benny* envolve não só a resolução da questão do rapto internacional, mas também a regulação das responsabilidades parentais, matéria para a qual seriam primariamente competentes os tribunais do Estado-Membro da residência habitual das crianças antes da deslocação ou retenção ilícitas (Irlanda; art. 9.º).

Contudo, como resulta de forma clara do início do artigo 9.º essa competência é sem prejuízo da competência atribuída nos termos de um pacto de jurisdição, previsto no artigo 10.º.

Aliás, para além das casos de concentração da competência em matéria de ações matrimoniais e de responsabilidade parental, a outra concentração que me parece muito útil na prática é a de concentrar a competência para a ação de regresso nos termos da Convenção da Haia de 1980 e para regular as responsabilidades parentais. Isso mesmo é indiciado no considerando n.º 43.

#+begin_quote
"(...) Se, no decurso do processo de regresso previsto na Convenção da Haia de 1980, os pais chegarem a acordo não só sobre o regresso ou a retenção da criança, mas também sobre outras matérias de responsabilidade parental, o presente regulamento deverá, em determinadas circunstâncias, permitir que eles acordem em que o tribunal chamado a pronunciar-se ao abrigo da Convenção da Haia de 1980 tenha competência para conferir efeitos jurídicos vinculativos ao seu acordo, incorporando-o numa decisão, aprovando-o ou utilizando qualquer outra forma prevista no direito e nos procedimentos nacionais. Os Estados-Membros que tenham concentrado a competência deverão, por conseguinte, considerar a possibilidade de permitir que o tribunal onde foi instaurado o processo de regresso ao abrigo da Convenção da Haia de 1980
exerça também a competência acordada ou aceite entre as partes nos termos do presente regulamento em matéria de responsabilidade parental quando tenha sido alcançado acordo entre as partes no decurso desse processo de
regresso." (Considerando n.º 43)
#+end_quote

*17. Condições para o estabelecimento de competência através de um pacto: 1.ª condição cumulativa: ligação estreita da criança ao Estado-Membro designado (art. 10.º, n.º 1, al. /a)/)*.

O pacto só será admissível quando haja uma ligação estreita entre a criança e o Estado-Membro designado no pacto. No artigo 10.º, n.º 1, al. /a)/ indica-se uma lista /exemplificativa/ de situações em que há um conexão estreita.

No nosso caso, verifica-se pelo menos uma das ligações indicadas (as crianças têm nacionalidade portuguesa).

*18. 2.ª condição cumulativa: existência de acordo entre as partes no processo (art. 10.º, n.º 1, al. /b)/)*. Resulta das duas subalíneas do artigo 10.º, n.º 1, al. /b)/, que o acordo pode ser extrajudicial e, nesse caso, pode ser efetuado até à data da instauração do processo /ou/ pode ser efetuado no decurso e dentro do processo. No nosso caso parece que o acordo seria feito durante o processo.

*Validade formal do acordo:* sendo o acordo efetuado durante e dentro do processo, as regras formais que devem ser seguidas são as do Estado-Membro do foro (art. 10.º, n.º 2 e considerando n.º 23), relevando-se que o tribunal deve assegurar que todas as partes foram informadas do seu direito de não aceitar a competência (art. 10.º, n.º 2). Trata-se de uma obrigação algo semelhante à que existe no artigo 26.º, n.º 2, do Regulamento Bruxelas I /bis/.

*Identificação das partes:* o acordo deve ser celebrado pelas pessoas que são (ou serão) partes no processo. Regra geral, serão os progenitores das crianças. Podem também ser outras pessoas que sejam os titulares do exercício das responsabilidades parentais (por exemplo, no caso de colocação de crianças numa instituição). Todavia, há que prestar atenção à jurisprudência do TJ proferida em sede de Bruxelas II /bis/:

- No Acórdão de 31 de maio de 2018, /Valcheva/, C-335/17, [[https://curia.europa.eu/juris/liste.jsf?nat=or&mat=or&pcs=Oor&jur=C%2CT%2CF&num=C-335%252F17&for=&jge=&dates=&language=pt&pro=&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&oqp=&td=%3BALL&avg=&lg=&page=1&cid=191678][EU:C:2018:359]], o TJ concluiu que os avós a quem foi atribuído um direito de visita eram titulares da responsabilidade da criança;

- No Acórdão de 19 de abril de 2018, /Saponaro/, C-565/16, [[https://curia.europa.eu/juris/liste.jsf?nat=or&mat=or&pcs=Oor&jur=C%2CT%2CF&num=C-565%252F16&for=&jge=&dates=&language=pt&pro=&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&oqp=&td=%3BALL&avg=&lgrec=nl&lg=&page=1&cid=192583][EU:C:2018:265]], o TJ referiu, quando ao procurador público grego:

  #+begin_quote
29      Há, portanto, que considerar que um procurador que, segundo o direito nacional, tem a qualidade de parte no processo em ações como a que está em causa no processo principal e que representa o interesse do menor, é uma parte no processo, na aceção do artigo 12.°, n.° 3, alínea b), do Regulamento n.° 2201/2003. Por conseguinte, a sua oposição a uma extensão de competência não pode ser ignorada.
  #+end_quote

*Pergunta aos formandos:* atendendo à jurisprudência do caso /Saponaro/ como deve ser caracterizada a participação do Ministério Público nos processos de respnsabilidade parental que correm termos nos tribunais portugueses? Deve ser considerado, ou não, uma parte de pleno direito?

A resposta a esta questão é muito importante, porque nos termos do artigo 10.º, n.º 1, al. /b)/, e n.º 2, 2.º parágrafo, as partes de pleno direito podem opor-se aos pactos de jurisdição; havendo oposição, o pacto não produz efeitos.

*19. 3.ª condição cumulativa: o exercício da competência pelo tribunal designado no pacto tem de ser /no superior interesse da criança/ (art. 10.º, n.º 1, al. /c)/)*. Em primeiro lugar, chama-se a atenção para o considerando 19:

#+begin_quote
As regras de competência em matéria de responsabilidade parental *são definidas em função do superior interesse da criança e devem ser aplicadas em função desse interesse*. *Todas as referências ao superior interesse da criança deverão ser interpretadas à luz do artigo 24.º da Carta dos Direitos Fundamentais da União Europeia («Carta») e da Convenção das Nações Unidas sobre os Direitos da Criança, de 20 de novembro de 1989 («Convenção das Nações Unidas sobre os Direitos da Criança»)*, aplicadas ao abrigo do direito e dos procedimentos nacionais. (negritos aditados)
#+end_quote

O artigo 24.º da Carta estabelece:

#+begin_quote
Artigo 24.º

*Direitos das crianças*

1. As crianças têm direito à proteção e aos cuidados necessários ao seu bem-estar. Podem exprimir livremente a sua opinião, que será tomada em consideração nos assuntos que lhes digam respeito, em função da sua idade e maturidade.
2. Todos os atos relativos às crianças, quer praticados por entidades públicas, quer por instituições privadas, terão primacialmente em conta o interesse superior da criança.
3. Todas as crianças têm o direito de manter regularmente relações pessoais e contactos diretos com ambos os progenitores, exceto se isso for contrário aos seus interesses.
#+end_quote

O artigo 3.º da CNUDC estabelece:

#+begin_quote
Artigo 3.º
1. Todas as decisões relativas a crianças, adoptadas por instituições públicas ou privadas de protecção social, por tribunais, autoridades administrativas ou órgãos legislativos, terão primacialmente em conta o interesse superior da criança.
2. Os Estados Partes comprometem-se a garantir à criança a protecção e os cuidados necessários ao seu bem-estar, tendo em conta os direitos e deveres dos pais, representantes legais ou outras pessoas que a tenham legalmente a seu cargo e, para este efeito, tomam todas as medidas legislativas e administrativas adequadas.
3. Os Estados Partes garantem que o funcionamento de instituições, serviços e estabelecimentos que têm crianças a seu cargo e asseguram a sua protecção seja conforme às normas fixadas pelas autoridades competentes, nomeadamente nos domínios da segurança e saúde, relativamente ao número e qualificação do seu pessoal, bem como quanto à existência de uma adequada fiscalização.
#+end_quote

O superior interesse da criança na jurisprudência do TJ:

- No Acórdão de 12 de novembro de 2014, /L/, C-656/13, [[https://curia.europa.eu/juris/liste.jsf?nat=or&mat=or&pcs=Oor&jur=C%2CT%2CF&num=C-656%252F13&for=&jge=&dates=&language=pt&pro=&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&oqp=&td=%3BALL&avg=&lgrec=en&lg=&page=1&cid=197974][EU:C:2014:2364]], o TJ esclareceu que a análise do superior interesse da criança tem de ser casuística:

  #+begin_quote
  58      Importa acrescentar que, quando é submetido um processo a um tribunal nos termos do artigo 12.°, n.° 3, do Regulamento n.° 2201/2003, *o superior interesse da criança só pode ser assegurado através de uma análise, em cada caso concreto, da questão de saber se a extensão de competência pretendida é compatível com esse superior interesse*, e que uma extensão de competência, nos termos do artigo 12.°, n.° 3, do Regulamento n.° 2201/2003, apenas produz efeitos para o processo específico submetido ao tribunal cuja competência é objeto de extensão (v., neste sentido, acórdão E, EU:C:2014:2246, n.os 47 e 49). (negritos aditados)
  #+end_quote

- No Acórdão de 19 de abril de 2018, /Saponaro/, C-565/16, [[https://curia.europa.eu/juris/liste.jsf?nat=or&mat=or&pcs=Oor&jur=C%2CT%2CF&num=C-565%252F16&for=&jge=&dates=&language=pt&pro=&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&oqp=&td=%3BALL&avg=&lgrec=nl&lg=&page=1&cid=192583][EU:C:2018:26]], esclareceu que a aceitação da competência não deve ser suscetível de ter um impacto negativo na situação do menor:

  #+begin_quote
  No Acórdão de 27 de outubro de 2016, D. (C-428/15, EU:C:2016:819, n.º 58), relativo à interpretação do artigo 15.º do Regulamento n.º 2201/2013, consagrado à transferência para um tribunal mais bem colocado para apreciar a ação, o Tribunal de Justiça concluiu que a exigência de que a transferência sirva o superior interesse da criança implica que o tribunal competente se certifique, à luz das circunstâncias concretas do processo, de que a transferência equacionada deste último para um tribunal de outro Estado-Membro não é suscetível de ter um impacto negativo na situação do menor.
  #+end_quote

*Pergunta para os formandos:* a aceitação da competência pelo tribunal português acarreta o prejuízo para a situação do menor?

A resposta a esta questão deve ser dada no caso concreto e é decisiva para a aceitação da competência. O pacto só produzirá os seus efeitos se o tribunal português considerar que o exercício da competência que lhe é atribuída pelo pacto respeita o superior interesse criança. Em suma: o tribunal tem uma palavra decisiva a dizer quanto a admissibilidde do pacto. Diria que neste caso, a aceitação da competência não acarreta prejuízo para as crianças, já que ela que vai permitir viabilizar o acordo que soluciona não só a situação de rapto internacional, como a regulação das responsabilidades parentais.


** *Questão 5:* Considere agora que não houve acordo entre os progenitores e  que o tribunal português de primeira instância proferiu uma decisão de regresso.
*** (i) O tribunal pode declará-la executória, independentemente de qualquer recurso?

*20. Direito processual civil internacional material: a possibilidade de declarar a decisão que ordena o regresso executoria*. Sim. Essa possibilidade é expressamente consagrada no pelo artigo 27.º, n.º 6:

#+begin_quote
"Uma decisão que ordene o regresso da criança pode ser declarada executória a título provisório, não obstante qualquer recurso, se o regresso da criança antes da decisão sobre o recurso for exigido pelo superior interesse da criança"
#+end_quote

*** (ii) /Quid iuris/ se *Ana*, antecipando que a decisão lhe seria desfavorável, se deslocou, com as crianças, para França.

*21. A possibilidade de execução noutros Estados-Membros das decisões que ordenam o regresso*. A decisão portuguesa de regresso pode ser executada em França (arts. 2.º, n.º 1, alínea /a)/, 35.º, n.º 1 e 36.º, n.º 1, alínea /c)/).

Tal significa que *Benny* tem dois caminhos alternativos que pode seguir: (i) pedir a execução da decisão de regresso portuguesa em França; ou (ii) instaurar nova ação, junto dos tribunais franceses, a pedir o regresso da criança.

Se optar por pedir a execução da decisão portuguesa precisa de apresentar:
1. cópia da decisão portuguesa (art. 35.º, n.º 1, alínea /a)/); e
2. certidão (art. 35.º, n.º 1, alínea /b)/).

A certidão é emitida pelo tribunal português de 1.ª instância (juízos de família e menores ou, na sua falta, juízos locais cíveis ou, na sua falta, juízos de competência genérica), nos termos do artigo 36.º, n.º 1, alínea /c)/ e segundo o formulário que consta como Anexo IV.

A certidão não é objeto de impugnação (art. 36.º, n.º 3), só podendo ser pedida a sua rectificação (art. 37.º)

** *Questão 6*: Admita agora que, após ouvir *Ana*, *Benny*, *Charles* e *Diane* o tribunal português proferiu uma decisão de não regresso. Durante a pendência do processo, *Benny* informou o tribunal português de que se encontra pendente, desde 1 de dezembro de 2022, em tribunal irlandês, uma ação relativa a regulação das responsabilidade parentais de *Charles* e *Diane*.
*** (i) Determine quais os tribunais que tinham competência internacional para regular o exercício das responsabilidades parentais.

*22. Competência em matéria de responsabilidades parentais nos casos de rapto internacional de crianças*. Sobre esta matéria dispõe o artigo 9.º do Regulamento Bruxelas II /ter/.

Sem prejuízo de um pacto de jurisdição - que nesta questão não foi celebrado - são internacionalmente competentes os tribunais do Estado-Membro da residência habitual da criança antes da deslocação ou retenção ilícitas (Irlanda; art. 9.º), pois na hipótese não se verifica nenhuma das exceções previstas nas alíneas /a)/ e /b)/ do referido preceito.

Os tribunais internacionalmente competentes em matéria de responsabilidades parentais eram os tribunais irlandeses.

/Pergunta aos formandos:/ não é o caso da hipótese, mas poder-se-ia aplicar o art. 9.º do Regulamento Bruxelas II /ter/, por exemplo, para atribuir competência internacional aos tribunais portugueses num caso em que uma criança com residência habitual em Portugal fosse deslocada ou retida ilicitamente num Estado que não é um Estado-Membro da União Europeia?

/Resposta:/ não. O TJ já esclareceu, em sede da regra paralela do Regulamento Bruxelas II /bis/ (art. 10.º), que:

#+begin_quote
"Resulta destas considerações que a regulamentação específica que o legislador da União quis instituir com a adoção do Regulamento n.º 2201/2003 visa os casos de raptos de crianças de um Estado‑Membro para outro. Daqui decorre que a regra de competência correspondente, a saber, a regra resultante do artigo 10.º do Regulamento n.º 2201/2003, não pode ser interpretada no sentido de que se aplica ao caso do rapto de uma criança para um Estado terceiro." (considerando n.º 57 do Acórdão de 24 de março de 2021, /SS contra MCP/, C-603/20 PPU, [[https://curia.europa.eu/juris/liste.jsf?oqp=&for=&mat=or&jge=&td=%3BALL&jur=C%2CT%2CF&num=C-603%252F20&page=1&dates=&pcs=Oor&lg=&pro=&nat=or&cit=none%252CC%252CCJ%252CR%252C2008E%252C%252C%252C%252C%252C%252C%252C%252C%252C%252Ctrue%252Cfalse%252Cfalse&language=pt&avg=&cid=7335098][EU:C:2021:231]])
#+end_quote

*** (ii) O tribunal português fundamenta a decisão de não regresso com base na oposição da criança. Como deve atuar o tribunal português?

*23. Procedimento no caso de decisão de recusa fundamentada /exclusivamente/ em risco grave da criança /ou/ na oposição da criança*. O artigo 29.º do Regulamento Bruxelas II /ter/ desenvolve as regras operacionais que já existiam no artigo 11.º, n.ºs 6 a 8, embora com algumas diferenças.

Em primeiro lugar, o procedimento apenas é aplicável nos casos em que a decisão de não regresso se baseie no artigo 13.º, alínea /b)/ (risco grave da criança) ou no artigo 13.º, segundo parágrafo (oposição da criança). Embora não resulte do artigo, diremos que também se aplica quando a decisão de não regresso se baseie exclusiva e cumulativamente nestes dois fundamentos (neste sentido, cf. título do Anexo I do Regulamento).

Estabelece-se uma obrigação de o tribunal que proferiu a decisão de não regresso (no caso, o tribunal português) informar o tribunal do Estado-Membro no qual está pendente uma ação de regulação do exercício das responsabilidades parentais, se ele souber que tal ação está pendente (no caso, o tribunal irlandês; cf. art. 29.º, n.º 3).

O tribunal português deve remeter ao tribunal irlandês onde a ação de regulação das responsabilidades parentais, /no prazo de um mês a contar da data em que foi proferida a decisão de não regresso/, os seguintes elementos:
1. cópia da decisão de não regresso; e
2. certidão utilizando o formulário que consta como Anexo I do Regulamento; e
3. transcrição, resumo ou atas das audições perante o tribunal e quaisquer outros documentos que considere pertinentes.

O tribunal pode remeter esta informação diretamente para o tribunal irlandês ou pode remeter a informação através das autoridades centrais.

Parece-me que a ideia é dar a conhecer ao tribunal que tem pendente a ação de regulação do exercício das responsabilidades parentais a decisão de não regresso, com dois objetivos:
1. Fomentar a comunicação entre tribunais e prover o tribunal que vai decidir sobre a regulação das responsabilidades parentais com informação que pode ser relevante (v.g. oposição da criança ao regresso ou avaliação, por outro tribunal, da situação de risco grave para a criança em caso de regresso); e
2. Promover a possibilidade de decisão privilegiada que reverta a decisão de não regresso (arts. 29.º, n.º 6, e 42.º, n.º 1, alínea /b)/).

/Pergunta aos formandos:/ o que sucede se a ação estiver pendente num tribunal de um Estado-Membro que /não é/ o da residência habitual da criança antes da deslocação ou retenção ilícitas (por exemplo, porque os progenitores fizeram um pacto de jurisdição, art. 10.º)?

/Resposta:/ questão difícil, mas eu diria que aí não lugar a reconhecimento privilegiado; só há lugar a reconhecimento nos termos normais.

Nos casos em que não esteja ainda pendente ação de regulação das responsabilidade parentais, o prazo alarga para /três meses/ e o quem deve informar e apresentar os documentos é a parte que instaurar a ação (art. 29.º, n.º 5).

/Pergunta para os formandos:/ será que estamos perante um ónus ou não atendendo à redação do artigo 29.º, n.º 6? Se não for cumprido o art. 29.º, n.º 3 ou n.º 5, pode haver uma decisão em matéria de responsabilidades parentais que pode beneficiar do regime de reconhecimento e execução de decisões privilegiadas?

#+begin_quote
"Não obstante uma decisão a que se refere o n.º 1, *qualquer* decisão sobre o mérito do direito de guarda resultante dos processos referidos nos n.ºs 3 e 5 que implique o regresso da criança é executória noutro Estado-Membro, em conformidade com o capítulo IV." (negritos aditados)
#+end_quote

/Resposta:/ parece-me que a resposta definitiva se retira da conjugação do artigo 29.º, n.º 6 com o artigo 47.º, em particular com o seu n.º 4:

#+begin_quote
"Sem prejuízo do n.º 3 do presente artigo, a certidão para uma decisão a que se refere o artigo 42.º, n.º 1, alínea b), só é emitida se, na sua decisão, o tribunal tiver tido em conta os motivos e os factos em que assentava a decisão anterior proferida noutro Estado-Membro nos termos do artigo 13.º, primeiro parágrafo, alínea b), ou do artigo 13.º, segundo
parágrafo, da Convenção de Haia de 1980."
#+end_quote

A luz destes dois preceitos eu diria que:
1. A preterição dos prazos /não/ deve afetar a aplicação do regime; porém
2. Se o tribunal da anterior residência habitual não for informado da decisão, ele não poderá tomar em conta os motivos e os factos em que assentava a decisão de não regresso e, como tal, não poderá emitir a certidão.

Todavia, vejam o considerando n.º 52.

*** (iii) O tribunal irlandês profere, em 13 de dezembro de 2022 e após ouvir *Ana*, *Benny*, *Charles* e *Diane*, uma decisão que atribui o direito de guarda em exclusivo a *Benny* e concede direitos de visita a *Ana*, fixando a residência habitual das crianças na Irlanda. Como pode esta decisão ser executada em Portugal?

*24. Os dois caminhos possíveis: reconhecimento e execução normal ou reconhecimento e execução de decisões privilegiadas*.

Regime de reconehcimento e execução normal das decisões em matéria de responsabilidades parentais (arts. 30.º e 34.º).

Neste caso, há que atender aos fundamentos de recusa de reconhecimento e execução (art. 39.º) e ao artigo 56.º, n.º 6.

O risco aqui era o de se entender que havia um fundamento de recusa assente na violação da ordem pública internacional do Estado Português, atento o superior interesse da criança, uma vez que se tinha previamente uma decisão de não regresso atendendo à oposição da criança.

/Pergunta para os formandos:/ parece-vos que seria um caso de impedir a execução com fundamento na violação da ordem pública internacional?

/Resposta:/ tenho imensas dúvidas.

Em alternativa, e os caminhos são verdadeiramente alternativos, podendo a parte que requer o reconhecimento e execução escolher livremente qualquer um deles, pode adotar-se o regime de reconhecimento e execução das decisões privilegiadas.

Chama-se a atenção para o artigo 47.º. A decisão irlandesa só pode seguir este caminho se (cf. artigo 47.º, n.º 3):
1. tiver ouvido todas as partes implicadas (o que sucedeu);
2. as crianças tiverem tido a oportunidade de expressar a sua opinião (o que sucedeu);
3. a decisão não foi proferida a revelia (o caso da hipótese) ou sendo-o, a parte revel foi citada em tempo útil e de forma a poder deduzir a sua defesa ou aceitou a decisão de forma inequívoca;
4. a decisão tiver tido em conta os motivos e factos em que assentava a decisão anterior de não regresso proferida pelo tribunal de outro Estado-Membro (não é dito na hipótese e disto depende a possibilidade de recorrer a este regime privilegiado).

A grande diferença dos regimes está nos fundamentos de recusa: o reconhecimento da decisão privilegiada só pode ocorrer com fundamento em decisão /posterior incompatível/ em matéria de responsabilidade parental em relação à mesma criança (art. 50.º). Adicionalmente a execução pode ser suspensa ou recusada nos casos do artigo 56.º, n.º 4 e 6.
